/**
 * What the reaction picker offers (F18).
 *
 * Presentation data, so it lives with the board rather than in the shared
 * contract: the server does not care which emoji a client puts in front of
 * people, only that what comes back is one emoji. Adding a row here needs no
 * migration and no agreement with any other module.
 *
 * A curated catalogue rather than every codepoint Unicode calls pictographic.
 * The full set runs past 1900 glyphs, most of them regional indicators and
 * clock faces nobody reaches for mid-brainstorm, and a grid that long buries
 * the ones people do want. These are the emoji in ordinary use, grouped the
 * way every picker groups them.
 *
 * Each entry is the glyph, what Unicode calls it, and the words someone might
 * type to find it. The terms are what makes the search box work at all: an
 * emoji carries no name of its own that a browser can be asked for, so anything
 * not written here is findable only by scrolling to it. The name is there for
 * the same reason: a reaction has to be sayable — in a heading, and to a screen
 * reader — and a list of search terms is not a name.
 *
 * The grids are laid out one entry per line and held that way with
 * `prettier-ignore`, so a category reads as a list you can scan for a
 * duplicate rather than as a reflowed paragraph of punctuation.
 */

import { reactionLabel, reactionName } from '@roundtable/shared';

/**
 * A glyph, what Unicode calls it, and the space-separated words that find it.
 *
 * The name is the one from Unicode's own emoji list rather than anything
 * invented here, so what a card says a reaction is matches what every other
 * app calls it. It is lower case as Unicode writes it; anywhere it starts a
 * line it is capitalised where it is shown.
 */
export type EmojiEntry = readonly [emoji: string, name: string, terms: string];

export interface EmojiGroup {
  /** Tab label, and the accessible name of the tab. */
  name: string;
  /** The glyph on the tab itself. */
  icon: string;
  emojis: readonly EmojiEntry[];
}

export const EMOJI_GROUPS: readonly EmojiGroup[] = [
  {
    name: 'Smileys',
    icon: '😀',
    // prettier-ignore
    emojis: [
      ['😀', 'grinning face', 'grinning grin happy smile face'],
      ['😃', 'grinning face with big eyes', 'smiley happy joy open smile'],
      ['😄', 'grinning face with smiling eyes', 'smile happy laugh eyes joy'],
      ['😁', 'beaming face with smiling eyes', 'beaming grin teeth happy'],
      ['😆', 'grinning squinting face', 'laughing satisfied haha laugh'],
      ['😅', 'grinning face with sweat', 'sweat smile relief nervous laugh'],
      ['🤣', 'rolling on the floor laughing', 'rofl rolling floor laughing lol'],
      ['😂', 'face with tears of joy', 'joy tears laughing cry lol funny'],
      ['🙂', 'slightly smiling face', 'slight smile fine ok'],
      ['🙃', 'upside-down face', 'upside down silly irony sarcasm'],
      ['😉', 'winking face', 'wink flirt joke'],
      ['😊', 'smiling face with smiling eyes', 'blush smile happy warm'],
      ['😇', 'smiling face with halo', 'innocent halo angel good'],
      ['🥰', 'smiling face with hearts', 'smiling hearts love adore'],
      ['😍', 'smiling face with heart-eyes', 'heart eyes love crush amazing'],
      ['🤩', 'star-struck', 'star struck excited amazed wow'],
      ['😘', 'face blowing a kiss', 'kiss blow heart'],
      ['😗', 'kissing face', 'kissing kiss'],
      ['😚', 'kissing face with closed eyes', 'kissing closed eyes kiss'],
      ['😙', 'kissing face with smiling eyes', 'kissing smiling eyes kiss'],
      ['🥲', 'smiling face with tear', 'smiling tear happy sad bittersweet'],
      ['😋', 'face savoring food', 'yum tasty delicious tongue savour'],
      ['😛', 'face with tongue', 'tongue out playful cheeky'],
      ['😜', 'winking face with tongue', 'winking tongue joke crazy'],
      ['🤪', 'zany face', 'zany crazy goofy wild silly'],
      ['😝', 'squinting face with tongue', 'squinting tongue silly yuck'],
      ['🤑', 'money-mouth face', 'money mouth rich dollar profit'],
      ['🤗', 'smiling face with open hands', 'hugging hug embrace warm'],
      ['🤭', 'face with hand over mouth', 'hand over mouth oops giggle'],
      ['🤫', 'shushing face', 'shushing quiet secret hush'],
      ['🤔', 'thinking face', 'thinking think hmm consider unsure'],
      ['🤐', 'zipper-mouth face', 'zipper mouth silent secret'],
      ['🤨', 'face with raised eyebrow', 'raised eyebrow skeptical suspicious doubt'],
      ['😐', 'neutral face', 'neutral blank meh deadpan'],
      ['😑', 'expressionless face', 'expressionless blank flat'],
      ['😶', 'face without mouth', 'no mouth speechless silence'],
      ['😏', 'smirking face', 'smirk smug knowing'],
      ['😒', 'unamused face', 'unamused annoyed unimpressed'],
      ['🙄', 'face with rolling eyes', 'rolling eyes exasperated whatever'],
      ['😬', 'grimacing face', 'grimacing awkward cringe yikes'],
      ['😌', 'relieved face', 'relieved calm content peace'],
      ['😔', 'pensive face', 'pensive sad down glum'],
      ['😪', 'sleepy face', 'sleepy tired drowsy'],
      ['🤤', 'drooling face', 'drooling drool hungry want'],
      ['😴', 'sleeping face', 'sleeping asleep zzz snore'],
      ['😷', 'face with medical mask', 'mask sick medical face'],
      ['🤒', 'face with thermometer', 'thermometer sick fever ill'],
      ['🤕', 'face with head-bandage', 'head bandage hurt injured'],
      ['🤢', 'nauseated face', 'nauseated sick disgusted gross'],
      ['🤮', 'face vomiting', 'vomiting sick puke gross'],
      ['🥵', 'hot face', 'hot heat sweating overheated'],
      ['🥶', 'cold face', 'cold freezing frozen ice'],
      ['🥴', 'woozy face', 'woozy dizzy drunk tipsy'],
      ['😵', 'face with crossed-out eyes', 'dizzy knocked out crossed eyes'],
      ['🤯', 'exploding head', 'exploding head mind blown shocked'],
      ['🤠', 'cowboy hat face', 'cowboy hat yeehaw'],
      ['🥳', 'partying face', 'partying party celebrate hat horn'],
      ['🥸', 'disguised face', 'disguised glasses incognito nose'],
      ['😎', 'smiling face with sunglasses', 'sunglasses cool shades'],
      ['🤓', 'nerd face', 'nerd geek glasses'],
      ['🧐', 'face with monocle', 'monocle inspect scrutiny examine'],
      ['😕', 'confused face', 'confused unsure puzzled'],
      ['😟', 'worried face', 'worried concerned anxious'],
      ['🙁', 'slightly frowning face', 'slight frown sad unhappy'],
      ['😮', 'face with open mouth', 'open mouth surprised wow oh'],
      ['😯', 'hushed face', 'hushed surprised stunned'],
      ['😲', 'astonished face', 'astonished shocked gasp'],
      ['😳', 'flushed face', 'flushed embarrassed blush shocked'],
      ['🥺', 'pleading face', 'pleading puppy eyes beg please'],
      ['😦', 'frowning face with open mouth', 'frowning open mouth worried'],
      ['😨', 'fearful face', 'fearful scared afraid'],
      ['😰', 'anxious face with sweat', 'anxious sweat nervous worried'],
      ['😥', 'sad but relieved face', 'sad relieved disappointed'],
      ['😢', 'crying face', 'crying tear sad upset'],
      ['😭', 'loudly crying face', 'sobbing loudly crying bawling sad'],
      ['😱', 'face screaming in fear', 'screaming fear scream shocked horror'],
      ['😖', 'confounded face', 'confounded frustrated distress'],
      ['😣', 'persevering face', 'persevere struggle strain'],
      ['😞', 'disappointed face', 'disappointed sad let down'],
      ['😓', 'downcast face with sweat', 'downcast sweat sad hard'],
      ['😩', 'weary face', 'weary tired frustrated'],
      ['😫', 'tired face', 'tired exhausted fed up'],
      ['🥱', 'yawning face', 'yawning bored tired'],
      ['😤', 'face with steam from nose', 'triumph steam angry huff determined'],
      ['😡', 'enraged face', 'pouting angry mad rage red'],
      ['😠', 'angry face', 'angry mad annoyed cross'],
      ['🤬', 'face with symbols on mouth', 'cursing swearing symbols angry'],
      ['😈', 'smiling face with horns', 'smiling devil imp mischief evil'],
      ['💀', 'skull', 'skull dead death bones'],
      ['💩', 'pile of poo', 'poop pile crap dung'],
      ['🤡', 'clown face', 'clown circus joker'],
      ['👻', 'ghost', 'ghost boo spooky halloween'],
      ['👽', 'alien', 'alien extraterrestrial ufo space'],
      ['🤖', 'robot', 'robot bot machine ai'],
      ['😺', 'grinning cat', 'grinning cat smile'],
      ['😹', 'cat with tears of joy', 'cat joy tears laughing'],
      ['😻', 'smiling cat with heart-eyes', 'heart eyes cat love'],
      ['🙀', 'weary cat', 'weary cat shocked scream'],
      ['😿', 'crying cat', 'crying cat sad'],
      ['😾', 'pouting cat', 'pouting cat angry'],
    ],
  },
  {
    name: 'Gestures',
    icon: '👍',
    // prettier-ignore
    emojis: [
      ['👋', 'waving hand', 'wave hand hello goodbye hi'],
      ['🤚', 'raised back of hand', 'raised back hand stop'],
      ['🖐️', 'hand with fingers splayed', 'hand fingers splayed five'],
      ['✋', 'raised hand', 'raised hand stop high five'],
      ['🖖', 'vulcan salute', 'vulcan salute spock live long'],
      ['👌', 'OK hand', 'ok hand perfect fine'],
      ['🤌', 'pinched fingers', 'pinched fingers italian gesture'],
      ['🤏', 'pinching hand', 'pinching small little bit'],
      ['✌️', 'victory hand', 'victory peace two fingers'],
      ['🤞', 'crossed fingers', 'crossed fingers luck hope'],
      ['🤟', 'love-you gesture', 'love you gesture hand'],
      ['🤘', 'sign of the horns', 'horns rock metal'],
      ['🤙', 'call me hand', 'call me shaka hang loose'],
      ['👈', 'backhand index pointing left', 'point left backhand'],
      ['👉', 'backhand index pointing right', 'point right backhand'],
      ['👆', 'backhand index pointing up', 'point up backhand above'],
      ['👇', 'backhand index pointing down', 'point down backhand below'],
      ['☝️', 'index pointing up', 'index point up one'],
      ['👍', 'thumbs up', 'thumbs up yes agree like approve good'],
      ['👎', 'thumbs down', 'thumbs down no disagree dislike bad'],
      ['✊', 'raised fist', 'raised fist solidarity power'],
      ['👊', 'oncoming fist', 'fist bump punch'],
      ['🤛', 'left-facing fist', 'left facing fist bump'],
      ['🤜', 'right-facing fist', 'right facing fist bump'],
      ['👏', 'clapping hands', 'clap applause bravo well done'],
      ['🙌', 'raising hands', 'raising hands celebrate praise hooray'],
      ['👐', 'open hands', 'open hands hug welcome'],
      ['🤲', 'palms up together', 'palms up together offer pray'],
      ['🤝', 'handshake', 'handshake deal agree partner'],
      ['🙏', 'folded hands', 'folded hands please thanks pray'],
      ['✍️', 'writing hand', 'writing hand write note'],
      ['💅', 'nail polish', 'nail polish manicure sass'],
      ['🤳', 'selfie', 'selfie phone camera'],
      ['💪', 'flexed biceps', 'flexed biceps strong muscle power'],
      ['🦾', 'mechanical arm', 'mechanical arm prosthetic robot'],
      ['🦿', 'mechanical leg', 'mechanical leg prosthetic robot'],
      ['🦵', 'leg', 'leg limb kick'],
      ['🦶', 'foot', 'foot kick stomp'],
      ['👂', 'ear', 'ear hear listen'],
      ['👃', 'nose', 'nose smell'],
      ['🧠', 'brain', 'brain mind smart think'],
      ['🫀', 'anatomical heart', 'anatomical heart organ pulse'],
      ['👀', 'eyes', 'eyes look watch see'],
      ['👁️', 'eye', 'eye look see'],
      ['👅', 'tongue', 'tongue taste lick'],
      ['👄', 'mouth', 'mouth lips'],
      ['💋', 'kiss mark', 'kiss mark lips lipstick'],
      ['🩸', 'drop of blood', 'blood drop donate'],
      ['👶', 'baby', 'baby infant child'],
      ['🧒', 'child', 'child kid young'],
      ['👦', 'boy', 'boy child'],
      ['👧', 'girl', 'girl child'],
      ['🧑', 'person', 'person adult someone'],
      ['👨', 'man', 'man adult male'],
      ['👩', 'woman', 'woman adult female'],
      ['🧓', 'older person', 'older person elder'],
      ['👴', 'old man', 'old man grandfather elder'],
      ['👵', 'old woman', 'old woman grandmother elder'],
      ['🙋', 'person raising hand', 'raising hand question volunteer me'],
      ['🙆', 'person gesturing OK', 'gesturing ok arms yes'],
      ['🙅', 'person gesturing NO', 'gesturing no stop refuse'],
      ['💁', 'person tipping hand', 'tipping hand information sassy'],
      ['🙇', 'person bowing', 'bowing sorry apology respect'],
      ['🤦', 'person facepalming', 'facepalm disbelief frustration'],
      ['🤷', 'person shrugging', 'shrug dunno whatever unsure'],
      ['🧑‍💻', 'technologist', 'technologist developer coding laptop'],
      ['🕵️', 'detective', 'detective spy investigate'],
      ['💂', 'guard', 'guard soldier'],
      ['🥷', 'ninja', 'ninja stealth'],
      ['🧑‍🚀', 'astronaut', 'astronaut space rocket'],
    ],
  },
  {
    name: 'Nature',
    icon: '🌿',
    // prettier-ignore
    emojis: [
      ['🐶', 'dog face', 'dog puppy pet face'],
      ['🐱', 'cat face', 'cat kitten pet face'],
      ['🐭', 'mouse face', 'mouse rodent'],
      ['🐹', 'hamster', 'hamster pet rodent'],
      ['🐰', 'rabbit face', 'rabbit bunny hare'],
      ['🦊', 'fox', 'fox clever'],
      ['🐻', 'bear', 'bear'],
      ['🐼', 'panda', 'panda bear'],
      ['🐨', 'koala', 'koala'],
      ['🐯', 'tiger face', 'tiger face'],
      ['🦁', 'lion', 'lion king'],
      ['🐮', 'cow face', 'cow face'],
      ['🐷', 'pig face', 'pig face'],
      ['🐸', 'frog', 'frog toad'],
      ['🐵', 'monkey face', 'monkey face'],
      ['🙈', 'see-no-evil monkey', 'see no evil monkey hide'],
      ['🙉', 'hear-no-evil monkey', 'hear no evil monkey'],
      ['🙊', 'speak-no-evil monkey', 'speak no evil monkey quiet'],
      ['🐒', 'monkey', 'monkey ape'],
      ['🦍', 'gorilla', 'gorilla ape'],
      ['🐔', 'chicken', 'chicken hen'],
      ['🐧', 'penguin', 'penguin'],
      ['🐦', 'bird', 'bird'],
      ['🐤', 'baby chick', 'chick baby bird'],
      ['🦆', 'duck', 'duck'],
      ['🦅', 'eagle', 'eagle bird'],
      ['🦉', 'owl', 'owl wise bird'],
      ['🦇', 'bat', 'bat vampire'],
      ['🐺', 'wolf', 'wolf'],
      ['🐗', 'boar', 'boar pig'],
      ['🐴', 'horse face', 'horse face'],
      ['🦄', 'unicorn', 'unicorn magic rare'],
      ['🐝', 'honeybee', 'bee honey buzz'],
      ['🐛', 'bug', 'bug caterpillar insect'],
      ['🦋', 'butterfly', 'butterfly transform'],
      ['🐌', 'snail', 'snail slow'],
      ['🐞', 'lady beetle', 'ladybug beetle luck'],
      ['🐜', 'ant', 'ant insect'],
      ['🕷️', 'spider', 'spider web'],
      ['🦂', 'scorpion', 'scorpion'],
      ['🐢', 'turtle', 'turtle tortoise slow'],
      ['🐍', 'snake', 'snake serpent'],
      ['🦎', 'lizard', 'lizard gecko'],
      ['🦖', 'T-Rex', 'dinosaur trex rex'],
      ['🐙', 'octopus', 'octopus tentacles'],
      ['🦑', 'squid', 'squid'],
      ['🦐', 'shrimp', 'shrimp prawn'],
      ['🦀', 'crab', 'crab'],
      ['🐡', 'blowfish', 'blowfish pufferfish'],
      ['🐠', 'tropical fish', 'tropical fish'],
      ['🐟', 'fish', 'fish'],
      ['🐬', 'dolphin', 'dolphin'],
      ['🐳', 'spouting whale', 'whale spouting'],
      ['🐋', 'whale', 'whale big'],
      ['🦈', 'shark', 'shark'],
      ['🐊', 'crocodile', 'crocodile alligator'],
      ['🐅', 'tiger', 'tiger'],
      ['🦓', 'zebra', 'zebra stripes'],
      ['🦛', 'hippopotamus', 'hippopotamus hippo'],
      ['🐘', 'elephant', 'elephant'],
      ['🦏', 'rhinoceros', 'rhinoceros rhino'],
      ['🐪', 'camel', 'camel desert'],
      ['🦒', 'giraffe', 'giraffe tall'],
      ['🦘', 'kangaroo', 'kangaroo jump'],
      ['🐄', 'cow', 'cow cattle'],
      ['🐎', 'horse', 'horse racehorse'],
      ['🐖', 'pig', 'pig hog'],
      ['🐑', 'ewe', 'sheep ewe wool'],
      ['🦙', 'llama', 'llama alpaca'],
      ['🐐', 'goat', 'goat'],
      ['🦌', 'deer', 'deer stag'],
      ['🐕', 'dog', 'dog'],
      ['🐈', 'cat', 'cat'],
      ['🦔', 'hedgehog', 'hedgehog'],
      ['🌵', 'cactus', 'cactus desert'],
      ['🎄', 'Christmas tree', 'christmas tree holiday'],
      ['🌲', 'evergreen tree', 'evergreen tree pine'],
      ['🌳', 'deciduous tree', 'deciduous tree'],
      ['🌴', 'palm tree', 'palm tree tropical'],
      ['🪴', 'potted plant', 'potted plant houseplant'],
      ['🌱', 'seedling', 'seedling sprout growth new'],
      ['🌿', 'herb', 'herb leaf plant'],
      ['☘️', 'shamrock', 'shamrock clover irish'],
      ['🍀', 'four leaf clover', 'four leaf clover luck lucky'],
      ['🍃', 'leaf fluttering in wind', 'leaves wind flutter'],
      ['🍂', 'fallen leaf', 'fallen leaves autumn fall'],
      ['🍁', 'maple leaf', 'maple leaf autumn canada'],
      ['🍄', 'mushroom', 'mushroom fungus'],
      ['🐚', 'spiral shell', 'shell spiral beach'],
      ['💐', 'bouquet', 'bouquet flowers gift'],
      ['🌷', 'tulip', 'tulip flower'],
      ['🌹', 'rose', 'rose flower love'],
      ['🥀', 'wilted flower', 'wilted flower dead'],
      ['🌺', 'hibiscus', 'hibiscus flower tropical'],
      ['🌸', 'cherry blossom', 'cherry blossom sakura flower spring'],
      ['🌼', 'blossom', 'blossom flower daisy'],
      ['🌻', 'sunflower', 'sunflower flower'],
      ['🌞', 'sun with face', 'sun face bright day'],
      ['🌝', 'full moon face', 'full moon face'],
      ['🌛', 'first quarter moon face', 'first quarter moon face'],
      ['🌚', 'new moon face', 'new moon face dark'],
      ['🌕', 'full moon', 'full moon night'],
      ['🌙', 'crescent moon', 'crescent moon night'],
      ['🌎', 'globe showing Americas', 'earth globe americas world planet'],
      ['🪐', 'ringed planet', 'ringed planet saturn space'],
      ['💫', 'dizzy', 'dizzy stars sparkle'],
      ['⭐', 'star', 'star favourite'],
      ['🌟', 'glowing star', 'glowing star sparkle shine'],
      ['✨', 'sparkles', 'sparkles magic shine new'],
      ['⚡', 'high voltage', 'high voltage lightning fast energy'],
      ['☄️', 'comet', 'comet space'],
      ['💥', 'collision', 'collision boom explosion impact'],
      ['🔥', 'fire', 'fire flame hot lit burn'],
      ['🌪️', 'tornado', 'tornado cyclone storm'],
      ['🌈', 'rainbow', 'rainbow pride colour'],
      ['☀️', 'sun', 'sun sunny bright clear'],
      ['⛅', 'sun behind cloud', 'sun behind cloud partly cloudy'],
      ['☁️', 'cloud', 'cloud cloudy overcast'],
      ['🌧️', 'cloud with rain', 'cloud rain rainy wet'],
      ['⛈️', 'cloud with lightning and rain', 'thunderstorm storm lightning rain'],
      ['❄️', 'snowflake', 'snowflake snow cold winter'],
      ['☃️', 'snowman', 'snowman snow winter'],
      ['⛄', 'snowman without snow', 'snowman without snow winter'],
      ['💨', 'dashing away', 'dashing wind fast gust'],
      ['💧', 'droplet', 'droplet water drop'],
      ['💦', 'sweat droplets', 'sweat droplets water splash'],
      ['☔', 'umbrella with rain drops', 'umbrella rain wet'],
      ['🌊', 'water wave', 'wave water ocean sea'],
    ],
  },
  {
    name: 'Food',
    icon: '🍕',
    // prettier-ignore
    emojis: [
      ['🍏', 'green apple', 'green apple fruit'],
      ['🍎', 'red apple', 'red apple fruit'],
      ['🍐', 'pear', 'pear fruit'],
      ['🍊', 'tangerine', 'tangerine orange fruit citrus'],
      ['🍋', 'lemon', 'lemon fruit citrus sour'],
      ['🍌', 'banana', 'banana fruit'],
      ['🍉', 'watermelon', 'watermelon fruit summer'],
      ['🍇', 'grapes', 'grapes fruit wine'],
      ['🍓', 'strawberry', 'strawberry fruit berry'],
      ['🫐', 'blueberries', 'blueberries fruit berry'],
      ['🍈', 'melon', 'melon fruit'],
      ['🍒', 'cherries', 'cherries fruit'],
      ['🍑', 'peach', 'peach fruit'],
      ['🥭', 'mango', 'mango fruit tropical'],
      ['🍍', 'pineapple', 'pineapple fruit tropical'],
      ['🥥', 'coconut', 'coconut fruit tropical'],
      ['🥝', 'kiwi fruit', 'kiwi fruit'],
      ['🍅', 'tomato', 'tomato vegetable salad'],
      ['🍆', 'eggplant', 'aubergine eggplant vegetable'],
      ['🥑', 'avocado', 'avocado fruit toast'],
      ['🥦', 'broccoli', 'broccoli vegetable green'],
      ['🥬', 'leafy green', 'leafy green lettuce vegetable'],
      ['🥒', 'cucumber', 'cucumber pickle vegetable'],
      ['🌶️', 'hot pepper', 'hot pepper chilli spicy'],
      ['🌽', 'ear of corn', 'corn maize cob'],
      ['🥕', 'carrot', 'carrot vegetable'],
      ['🧄', 'garlic', 'garlic'],
      ['🧅', 'onion', 'onion'],
      ['🥔', 'potato', 'potato'],
      ['🍠', 'roasted sweet potato', 'roasted sweet potato yam'],
      ['🥐', 'croissant', 'croissant pastry bread'],
      ['🥯', 'bagel', 'bagel bread'],
      ['🍞', 'bread', 'bread loaf'],
      ['🥖', 'baguette bread', 'baguette bread french'],
      ['🧀', 'cheese wedge', 'cheese wedge'],
      ['🥚', 'egg', 'egg'],
      ['🍳', 'cooking', 'cooking fried egg pan breakfast'],
      ['🧈', 'butter', 'butter'],
      ['🥞', 'pancakes', 'pancakes breakfast stack'],
      ['🧇', 'waffle', 'waffle breakfast'],
      ['🥓', 'bacon', 'bacon breakfast'],
      ['🍔', 'hamburger', 'hamburger burger fast food'],
      ['🍟', 'french fries', 'fries chips fast food'],
      ['🍕', 'pizza', 'pizza slice'],
      ['🌭', 'hot dog', 'hot dog sausage'],
      ['🥪', 'sandwich', 'sandwich lunch'],
      ['🌮', 'taco', 'taco mexican'],
      ['🌯', 'burrito', 'burrito wrap mexican'],
      ['🥙', 'stuffed flatbread', 'stuffed flatbread kebab pita'],
      ['🧆', 'falafel', 'falafel'],
      ['🥘', 'shallow pan of food', 'shallow pan of food paella'],
      ['🍝', 'spaghetti', 'spaghetti pasta italian'],
      ['🍜', 'steaming bowl', 'steaming bowl ramen noodles'],
      ['🍲', 'pot of food', 'pot of food stew soup'],
      ['🍛', 'curry rice', 'curry rice'],
      ['🍣', 'sushi', 'sushi japanese'],
      ['🍱', 'bento box', 'bento box japanese lunch'],
      ['🥟', 'dumpling', 'dumpling gyoza'],
      ['🍤', 'fried shrimp', 'fried shrimp prawn tempura'],
      ['🍙', 'rice ball', 'rice ball onigiri'],
      ['🍚', 'cooked rice', 'cooked rice'],
      ['🍥', 'fish cake with swirl', 'fish cake narutomaki'],
      ['🥠', 'fortune cookie', 'fortune cookie'],
      ['🍦', 'soft ice cream', 'soft ice cream dessert'],
      ['🍰', 'shortcake', 'shortcake cake slice dessert'],
      ['🎂', 'birthday cake', 'birthday cake celebrate'],
      ['🧁', 'cupcake', 'cupcake dessert'],
      ['🥧', 'pie', 'pie dessert'],
      ['🍫', 'chocolate bar', 'chocolate bar sweet'],
      ['🍬', 'candy', 'candy sweet'],
      ['🍭', 'lollipop', 'lollipop candy sweet'],
      ['🍩', 'doughnut', 'doughnut donut sweet'],
      ['🍪', 'cookie', 'cookie biscuit sweet'],
      ['☕', 'hot beverage', 'hot beverage coffee tea'],
      ['🍵', 'teacup without handle', 'teacup tea green'],
      ['🧃', 'beverage box', 'beverage box juice'],
      ['🥤', 'cup with straw', 'cup straw soda drink'],
      ['🧋', 'bubble tea', 'bubble tea boba'],
      ['🍺', 'beer mug', 'beer mug pint'],
      ['🍻', 'clinking beer mugs', 'clinking beer mugs cheers'],
      ['🥂', 'clinking glasses', 'clinking glasses cheers celebrate toast'],
      ['🍷', 'wine glass', 'wine glass red'],
      ['🥃', 'tumbler glass', 'tumbler whisky glass'],
      ['🍸', 'cocktail glass', 'cocktail martini glass'],
      ['🍾', 'bottle with popping cork', 'bottle popping champagne celebrate'],
      ['🧉', 'mate', 'mate drink'],
      ['🧊', 'ice', 'ice cube cold frozen'],
    ],
  },
  {
    name: 'Activity',
    icon: '⚽',
    // prettier-ignore
    emojis: [
      ['⚽', 'soccer ball', 'soccer football ball sport'],
      ['🏀', 'basketball', 'basketball ball sport'],
      ['🏈', 'american football', 'american football ball sport'],
      ['⚾', 'baseball', 'baseball ball sport'],
      ['🥎', 'softball', 'softball ball sport'],
      ['🎾', 'tennis', 'tennis ball sport'],
      ['🏐', 'volleyball', 'volleyball ball sport'],
      ['🏉', 'rugby football', 'rugby football ball sport'],
      ['🥏', 'flying disc', 'flying disc frisbee'],
      ['🎱', 'pool 8 ball', 'pool 8 ball billiards snooker'],
      ['🏓', 'ping pong', 'ping pong table tennis'],
      ['🏸', 'badminton', 'badminton shuttlecock'],
      ['🥅', 'goal net', 'goal net sport'],
      ['⛳', 'flag in hole', 'golf flag hole'],
      ['🏹', 'bow and arrow', 'bow and arrow archery target'],
      ['🎣', 'fishing pole', 'fishing pole fish'],
      ['🥊', 'boxing glove', 'boxing glove fight'],
      ['🥋', 'martial arts uniform', 'martial arts uniform karate judo'],
      ['🎽', 'running shirt', 'running shirt sash race'],
      ['🛹', 'skateboard', 'skateboard skate'],
      ['🛼', 'roller skate', 'roller skate'],
      ['🛷', 'sled', 'sled sledge snow'],
      ['⛸️', 'ice skate', 'ice skate skating'],
      ['🥌', 'curling stone', 'curling stone'],
      ['🎿', 'skis', 'skis skiing snow'],
      ['⛷️', 'skier', 'skier skiing snow'],
      ['🏂', 'snowboarder', 'snowboarder snowboard snow'],
      ['🏋️', 'person lifting weights', 'weight lifting gym workout'],
      ['🤸', 'person cartwheeling', 'cartwheel gymnastics'],
      ['🤺', 'person fencing', 'fencing sword'],
      ['🤾', 'person playing handball', 'handball sport'],
      ['🏌️', 'person golfing', 'golfing golf swing'],
      ['🏇', 'horse racing', 'horse racing jockey'],
      ['🧘', 'person in lotus position', 'lotus position yoga meditation calm'],
      ['🏄', 'person surfing', 'surfing surf wave'],
      ['🏊', 'person swimming', 'swimming swim pool'],
      ['🤽', 'person playing water polo', 'water polo'],
      ['🚣', 'person rowing boat', 'rowing boat row'],
      ['🚴', 'person biking', 'biking cycling bicycle'],
      ['🚵', 'person mountain biking', 'mountain biking cycling'],
      ['🎪', 'circus tent', 'circus tent carnival'],
      ['🎭', 'performing arts', 'performing arts theatre drama masks'],
      ['🎨', 'artist palette', 'artist palette paint art design'],
      ['🎬', 'clapper board', 'clapper board film movie action'],
      ['🎤', 'microphone', 'microphone sing mic'],
      ['🎧', 'headphone', 'headphone music listen audio'],
      ['🎼', 'musical score', 'musical score sheet music'],
      ['🎹', 'musical keyboard', 'musical keyboard piano'],
      ['🥁', 'drum', 'drum beat'],
      ['🎷', 'saxophone', 'saxophone jazz'],
      ['🎺', 'trumpet', 'trumpet brass'],
      ['🎸', 'guitar', 'guitar rock'],
      ['🎻', 'violin', 'violin strings'],
      ['🎲', 'game die', 'game die dice random chance'],
      ['♟️', 'chess pawn', 'chess pawn strategy'],
      ['🎯', 'bullseye', 'direct hit bullseye target goal'],
      ['🎳', 'bowling', 'bowling strike pins'],
      ['🎮', 'video game', 'video game controller gaming'],
      ['🕹️', 'joystick', 'joystick arcade gaming'],
      ['🧩', 'puzzle piece', 'puzzle piece jigsaw fit'],
      ['🚗', 'automobile', 'car automobile drive'],
      ['🚕', 'taxi', 'taxi cab'],
      ['🚌', 'bus', 'bus'],
      ['🏎️', 'racing car', 'racing car fast speed'],
      ['🚓', 'police car', 'police car'],
      ['🚑', 'ambulance', 'ambulance emergency'],
      ['🚒', 'fire engine', 'fire engine truck'],
      ['🚚', 'delivery truck', 'delivery truck lorry'],
      ['🚜', 'tractor', 'tractor farm'],
      ['🛵', 'motor scooter', 'motor scooter moped'],
      ['🏍️', 'motorcycle', 'motorcycle motorbike'],
      ['🚲', 'bicycle', 'bicycle bike cycle'],
      ['✈️', 'airplane', 'airplane flight travel plane'],
      ['🚀', 'rocket', 'rocket launch ship fast space'],
      ['🛸', 'flying saucer', 'flying saucer ufo alien'],
      ['🚁', 'helicopter', 'helicopter'],
      ['⛵', 'sailboat', 'sailboat sailing yacht'],
      ['🚤', 'speedboat', 'speedboat boat'],
      ['🛳️', 'passenger ship', 'passenger ship cruise'],
      ['🚂', 'locomotive', 'locomotive train steam'],
      ['🗺️', 'world map', 'world map travel plan'],
      ['🗿', 'moai', 'moai statue stone'],
      ['🗽', 'Statue of Liberty', 'statue of liberty new york'],
      ['🗼', 'Tokyo tower', 'tokyo tower'],
      ['🏰', 'castle', 'castle fortress'],
      ['🎡', 'ferris wheel', 'ferris wheel fair'],
      ['🎢', 'roller coaster', 'roller coaster theme park'],
      ['🎠', 'carousel horse', 'carousel horse fair'],
      ['⛲', 'fountain', 'fountain water'],
      ['🏖️', 'beach with umbrella', 'beach umbrella holiday sand'],
      ['🏝️', 'desert island', 'desert island beach tropical'],
      ['🏔️', 'snow-capped mountain', 'snow capped mountain peak'],
      ['🌋', 'volcano', 'volcano eruption lava'],
      ['🏕️', 'camping', 'camping tent outdoors'],
      ['🏡', 'house with garden', 'house with garden home'],
      ['🏢', 'office building', 'office building work'],
      ['🏫', 'school', 'school university education'],
      ['🏥', 'hospital', 'hospital medical'],
      ['⛺', 'tent', 'tent camping'],
      ['🌅', 'sunrise', 'sunrise morning dawn'],
      ['🌄', 'sunrise over mountains', 'sunrise over mountains morning'],
      ['🌆', 'cityscape at dusk', 'cityscape dusk evening city'],
      ['🌃', 'night with stars', 'night with stars city'],
      ['🌉', 'bridge at night', 'bridge at night'],
      ['🎇', 'sparkler', 'sparkler firework celebrate'],
      ['🎆', 'fireworks', 'fireworks celebrate new year'],
      ['🎉', 'party popper', 'party popper celebrate congrats hooray'],
      ['🎊', 'confetti ball', 'confetti ball celebrate party'],
      ['🎈', 'balloon', 'balloon party celebrate'],
      ['🎁', 'wrapped gift', 'wrapped gift present birthday'],
    ],
  },
  {
    name: 'Objects',
    icon: '💡',
    // prettier-ignore
    emojis: [
      ['⌚', 'watch', 'watch time wrist'],
      ['📱', 'mobile phone', 'mobile phone smartphone cell'],
      ['💻', 'laptop', 'laptop computer work'],
      ['⌨️', 'keyboard', 'keyboard typing'],
      ['🖥️', 'desktop computer', 'desktop computer monitor screen'],
      ['🖨️', 'printer', 'printer print'],
      ['🖱️', 'computer mouse', 'computer mouse click'],
      ['💽', 'computer disk', 'minidisc computer disk'],
      ['💾', 'floppy disk', 'floppy disk save'],
      ['💿', 'optical disk', 'optical disk cd'],
      ['📷', 'camera', 'camera photo'],
      ['📸', 'camera with flash', 'camera with flash photo'],
      ['📹', 'video camera', 'video camera record'],
      ['🎥', 'movie camera', 'movie camera film'],
      ['📽️', 'film projector', 'film projector cinema'],
      ['📞', 'telephone receiver', 'telephone receiver call'],
      ['☎️', 'telephone', 'telephone landline call'],
      ['📟', 'pager', 'pager beeper'],
      ['📠', 'fax machine', 'fax machine'],
      ['📺', 'television', 'television tv screen'],
      ['📻', 'radio', 'radio broadcast'],
      ['🎙️', 'studio microphone', 'studio microphone podcast record'],
      ['⏱️', 'stopwatch', 'stopwatch timer'],
      ['⏰', 'alarm clock', 'alarm clock wake time'],
      ['⏳', 'hourglass not done', 'hourglass flowing time waiting'],
      ['📡', 'satellite antenna', 'satellite antenna signal'],
      ['🔋', 'battery', 'battery power charge'],
      ['🔌', 'electric plug', 'electric plug power'],
      ['💡', 'light bulb', 'light bulb idea insight bright'],
      ['🔦', 'flashlight', 'flashlight torch light'],
      ['🕯️', 'candle', 'candle light'],
      ['🧯', 'fire extinguisher', 'fire extinguisher safety'],
      ['🛢️', 'oil drum', 'oil drum barrel'],
      ['💸', 'money with wings', 'money with wings spending cost'],
      ['💵', 'dollar banknote', 'dollar banknote money cash'],
      ['💰', 'money bag', 'money bag budget rich'],
      ['💳', 'credit card', 'credit card payment'],
      ['💎', 'gem stone', 'gem stone diamond precious'],
      ['⚖️', 'balance scale', 'balance scale justice weigh trade off'],
      ['🪜', 'ladder', 'ladder climb'],
      ['🧰', 'toolbox', 'toolbox tools'],
      ['🔧', 'wrench', 'wrench spanner fix tool'],
      ['🔨', 'hammer', 'hammer build tool'],
      ['⚒️', 'hammer and pick', 'hammer and pick tools'],
      ['🛠️', 'hammer and wrench', 'hammer and wrench tools build maintenance'],
      ['⛏️', 'pick', 'pick mine tool'],
      ['🔩', 'nut and bolt', 'nut and bolt hardware'],
      ['⚙️', 'gear', 'gear cog settings mechanism'],
      ['🧱', 'brick', 'brick wall build'],
      ['⛓️', 'chains', 'chains links blocked'],
      ['🧲', 'magnet', 'magnet attract'],
      ['🔫', 'water pistol', 'water pistol gun'],
      ['💣', 'bomb', 'bomb explode risk'],
      ['🧨', 'firecracker', 'firecracker dynamite'],
      ['🪓', 'axe', 'axe chop'],
      ['🔪', 'kitchen knife', 'kitchen knife cut chef'],
      ['🛡️', 'shield', 'shield protect defence'],
      ['🚬', 'cigarette', 'cigarette smoking'],
      ['⚰️', 'coffin', 'coffin dead funeral'],
      ['🏺', 'amphora', 'amphora vase pot'],
      ['🔮', 'crystal ball', 'crystal ball future predict fortune'],
      ['📿', 'prayer beads', 'prayer beads'],
      ['🧿', 'nazar amulet', 'nazar amulet evil eye'],
      ['💈', 'barber pole', 'barber pole'],
      ['⚗️', 'alembic', 'alembic chemistry experiment'],
      ['🔭', 'telescope', 'telescope stars vision look ahead'],
      ['🔬', 'microscope', 'microscope research detail science'],
      ['🕳️', 'hole', 'hole gap'],
      ['💊', 'pill', 'pill medicine drug'],
      ['💉', 'syringe', 'syringe injection vaccine'],
      ['🩹', 'adhesive bandage', 'adhesive bandage plaster fix patch'],
      ['🩺', 'stethoscope', 'stethoscope doctor health check'],
      ['🚪', 'door', 'door entry exit'],
      ['🛗', 'elevator', 'elevator lift'],
      ['🪑', 'chair', 'chair seat'],
      ['🚿', 'shower', 'shower wash'],
      ['🛁', 'bathtub', 'bathtub bath'],
      ['🧴', 'lotion bottle', 'lotion bottle soap'],
      ['🧷', 'safety pin', 'safety pin'],
      ['🧹', 'broom', 'broom sweep clean tidy'],
      ['🧺', 'basket', 'basket laundry'],
      ['🧻', 'roll of paper', 'roll of paper toilet'],
      ['🪣', 'bucket', 'bucket pail'],
      ['🧼', 'soap', 'soap wash clean'],
      ['🪥', 'toothbrush', 'toothbrush'],
      ['🧽', 'sponge', 'sponge clean'],
      ['🔑', 'key', 'key unlock access'],
      ['🗝️', 'old key', 'old key unlock secret'],
      ['🔒', 'locked', 'locked lock secure private'],
      ['🔓', 'unlocked', 'unlocked open access'],
      ['📔', 'notebook with decorative cover', 'notebook decorative cover'],
      ['📕', 'closed book', 'closed book read'],
      ['📖', 'open book', 'open book read study'],
      ['📗', 'green book', 'green book'],
      ['📚', 'books', 'books library reading'],
      ['📓', 'notebook', 'notebook notes'],
      ['📒', 'ledger', 'ledger accounts'],
      ['📃', 'page with curl', 'page with curl document'],
      ['📜', 'scroll', 'scroll document history'],
      ['📄', 'page facing up', 'page facing up document file'],
      ['📰', 'newspaper', 'newspaper news'],
      ['🗞️', 'rolled-up newspaper', 'rolled up newspaper news'],
      ['📑', 'bookmark tabs', 'bookmark tabs sections'],
      ['🔖', 'bookmark', 'bookmark save'],
      ['🏷️', 'label', 'label tag'],
      ['✉️', 'envelope', 'envelope email letter mail'],
      ['📩', 'envelope with arrow', 'envelope with arrow send mail'],
      ['📤', 'outbox tray', 'outbox tray send out'],
      ['📥', 'inbox tray', 'inbox tray receive in'],
      ['📦', 'package', 'package box parcel ship'],
      ['📫', 'closed mailbox with raised flag', 'closed mailbox raised flag mail'],
      ['📬', 'open mailbox with raised flag', 'open mailbox raised flag mail'],
      ['📮', 'postbox', 'postbox mail'],
      ['🗳️', 'ballot box with ballot', 'ballot box vote'],
      ['✏️', 'pencil', 'pencil write edit note'],
      ['✒️', 'black nib', 'black nib pen write'],
      ['🖋️', 'fountain pen', 'fountain pen write sign'],
      ['🖊️', 'pen', 'pen write'],
      ['🖌️', 'paintbrush', 'paintbrush paint art'],
      ['🖍️', 'crayon', 'crayon colour draw'],
      ['📝', 'memo', 'memo note write pencil paper'],
      ['💼', 'briefcase', 'briefcase work business'],
      ['📁', 'file folder', 'file folder directory'],
      ['📂', 'open file folder', 'open file folder directory'],
      ['🗂️', 'card index dividers', 'card index dividers organise'],
      ['📅', 'calendar', 'calendar date schedule'],
      ['📆', 'tear-off calendar', 'tear off calendar date'],
      ['🗒️', 'spiral notepad', 'spiral notepad notes'],
      ['🗓️', 'spiral calendar', 'spiral calendar schedule'],
      ['📇', 'card index', 'card index contacts'],
      ['📈', 'chart increasing', 'chart increasing growth up trend'],
      ['📉', 'chart decreasing', 'chart decreasing down decline'],
      ['📊', 'bar chart', 'bar chart data metrics'],
      ['📋', 'clipboard', 'clipboard list tasks'],
      ['📌', 'pushpin', 'pushpin pin location'],
      ['📍', 'round pushpin', 'round pushpin location here'],
      ['📎', 'paperclip', 'paperclip attach'],
      ['🖇️', 'linked paperclips', 'linked paperclips attach'],
      ['📏', 'straight ruler', 'straight ruler measure'],
      ['📐', 'triangular ruler', 'triangular ruler measure angle'],
      ['✂️', 'scissors', 'scissors cut trim'],
      ['🗃️', 'card file box', 'card file box archive'],
      ['🗄️', 'file cabinet', 'file cabinet archive storage'],
      ['🗑️', 'wastebasket', 'wastebasket bin delete trash'],
    ],
  },
  {
    name: 'Symbols',
    icon: '❤️',
    // prettier-ignore
    emojis: [
      ['❤️', 'red heart', 'red heart love like'],
      ['🧡', 'orange heart', 'orange heart love'],
      ['💛', 'yellow heart', 'yellow heart love'],
      ['💚', 'green heart', 'green heart love'],
      ['💙', 'blue heart', 'blue heart love'],
      ['💜', 'purple heart', 'purple heart love'],
      ['🖤', 'black heart', 'black heart love dark'],
      ['🤍', 'white heart', 'white heart love'],
      ['🤎', 'brown heart', 'brown heart love'],
      ['💔', 'broken heart', 'broken heart sad breakup'],
      ['❣️', 'heart exclamation', 'heart exclamation love'],
      ['💕', 'two hearts', 'two hearts love'],
      ['💞', 'revolving hearts', 'revolving hearts love'],
      ['💓', 'beating heart', 'beating heart love pulse'],
      ['💗', 'growing heart', 'growing heart love'],
      ['💖', 'sparkling heart', 'sparkling heart love'],
      ['💘', 'heart with arrow', 'heart with arrow cupid love'],
      ['💝', 'heart with ribbon', 'heart with ribbon gift love'],
      ['💟', 'heart decoration', 'heart decoration love'],
      ['☮️', 'peace symbol', 'peace symbol'],
      ['✝️', 'latin cross', 'latin cross christian'],
      ['☪️', 'star and crescent', 'star and crescent islam'],
      ['🕉️', 'om', 'om hindu'],
      ['☸️', 'wheel of dharma', 'wheel of dharma buddhism'],
      ['✡️', 'star of David', 'star of david judaism'],
      ['🔯', 'dotted six-pointed star', 'six pointed star'],
      ['🕎', 'menorah', 'menorah judaism'],
      ['☯️', 'yin yang', 'yin yang balance'],
      ['☦️', 'orthodox cross', 'orthodox cross'],
      ['🛐', 'place of worship', 'place of worship'],
      ['♈', 'Aries', 'aries zodiac'],
      ['♉', 'Taurus', 'taurus zodiac'],
      ['♊', 'Gemini', 'gemini zodiac'],
      ['♋', 'Cancer', 'cancer zodiac'],
      ['♌', 'Leo', 'leo zodiac'],
      ['♍', 'Virgo', 'virgo zodiac'],
      ['♎', 'Libra', 'libra zodiac'],
      ['♏', 'Scorpio', 'scorpio zodiac'],
      ['♐', 'Sagittarius', 'sagittarius zodiac'],
      ['♑', 'Capricorn', 'capricorn zodiac'],
      ['♒', 'Aquarius', 'aquarius zodiac'],
      ['♓', 'Pisces', 'pisces zodiac'],
      ['🆔', 'ID button', 'id button identity'],
      ['⚛️', 'atom symbol', 'atom science physics'],
      ['🉑', 'Japanese “acceptable” button', 'japanese acceptable button'],
      ['☢️', 'radioactive', 'radioactive warning nuclear'],
      ['☣️', 'biohazard', 'biohazard warning'],
      ['📴', 'mobile phone off', 'mobile phone off'],
      ['📳', 'vibration mode', 'vibration mode phone'],
      ['🈶', 'Japanese “not free of charge” button', 'japanese not free of charge button'],
      ['🈚', 'Japanese “free of charge” button', 'japanese free of charge button'],
      ['🈸', 'Japanese “application” button', 'japanese application button'],
      ['🈺', 'Japanese “open for business” button', 'japanese open for business button'],
      ['🈷️', 'Japanese “monthly amount” button', 'japanese monthly amount button'],
      ['✴️', 'eight-pointed star', 'eight pointed star'],
      ['🆚', 'VS button', 'vs button versus'],
      ['💮', 'white flower', 'white flower well done'],
      ['🉐', 'Japanese “bargain” button', 'japanese bargain button'],
      ['㊙️', 'Japanese “secret” button', 'japanese secret button'],
      ['㊗️', 'Japanese “congratulations” button', 'japanese congratulations button'],
      ['🈴', 'Japanese “passing grade” button', 'japanese passing grade button'],
      ['🈵', 'Japanese “no vacancy” button', 'japanese no vacancy button'],
      ['🈹', 'Japanese “discount” button', 'japanese discount button'],
      ['🈲', 'Japanese “prohibited” button', 'japanese prohibited button'],
      ['🅰️', 'A button (blood type)', 'a button blood type'],
      ['🅱️', 'B button (blood type)', 'b button blood type'],
      ['🆎', 'AB button (blood type)', 'ab button blood type'],
      ['🆑', 'CL button', 'cl button'],
      ['🅾️', 'O button (blood type)', 'o button blood type'],
      ['🆘', 'SOS button', 'sos button help emergency'],
      ['❌', 'cross mark', 'cross mark no wrong cancel'],
      ['⭕', 'hollow red circle', 'hollow red circle correct'],
      ['🛑', 'stop sign', 'stop sign halt'],
      ['⛔', 'no entry', 'no entry forbidden'],
      ['📛', 'name badge', 'name badge'],
      ['🚫', 'prohibited', 'prohibited no forbidden'],
      ['💯', 'hundred points', 'hundred points perfect score full marks'],
      ['💢', 'anger symbol', 'anger symbol mad'],
      ['♨️', 'hot springs', 'hot springs steam'],
      ['🚷', 'no pedestrians', 'no pedestrians'],
      ['🚯', 'no littering', 'no littering'],
      ['🚳', 'no bicycles', 'no bicycles'],
      ['🚱', 'non-potable water', 'non potable water'],
      ['🔞', 'no one under eighteen', 'no one under eighteen adult'],
      ['📵', 'no mobile phones', 'no mobile phones'],
      ['❗', 'red exclamation mark', 'exclamation mark important'],
      ['❕', 'white exclamation mark', 'white exclamation mark'],
      ['❓', 'red question mark', 'question mark ask unclear'],
      ['❔', 'white question mark', 'white question mark'],
      ['‼️', 'double exclamation mark', 'double exclamation urgent'],
      ['⁉️', 'exclamation question mark', 'exclamation question surprise'],
      ['🔅', 'dim button', 'dim button low brightness'],
      ['🔆', 'bright button', 'bright button high brightness'],
      ['〽️', 'part alternation mark', 'part alternation mark'],
      ['⚠️', 'warning', 'warning caution risk'],
      ['🚸', 'children crossing', 'children crossing'],
      ['🔱', 'trident emblem', 'trident emblem'],
      ['⚜️', 'fleur-de-lis', 'fleur de lis'],
      ['🔰', 'Japanese symbol for beginner', 'japanese symbol for beginner'],
      ['♻️', 'recycling symbol', 'recycling symbol reuse green'],
      ['✅', 'check mark button', 'check mark button done yes complete'],
      ['🈯', 'Japanese “reserved” button', 'japanese reserved button'],
      ['💹', 'chart increasing with yen', 'chart increasing with yen money up'],
      ['❇️', 'sparkle', 'sparkle'],
      ['✳️', 'eight-spoked asterisk', 'eight spoked asterisk'],
      ['❎', 'cross mark button', 'cross mark button no'],
      ['🌐', 'globe with meridians', 'globe with meridians web internet global'],
      ['💠', 'diamond with a dot', 'diamond with a dot'],
      ['Ⓜ️', 'circled M', 'circled m metro'],
      ['🌀', 'cyclone', 'cyclone spiral swirl'],
      ['💤', 'ZZZ', 'zzz sleep bored'],
      ['🏧', 'ATM sign', 'atm sign cash'],
      ['🚾', 'water closet', 'water closet toilet'],
      ['♿', 'wheelchair symbol', 'wheelchair symbol accessible accessibility'],
      ['🅿️', 'P button', 'p button parking'],
      ['🈳', 'Japanese “vacancy” button', 'japanese vacancy button'],
      ['🈂️', 'Japanese “service charge” button', 'japanese service charge button'],
      ['🛂', 'passport control', 'passport control border'],
      ['🛃', 'customs', 'customs border'],
      ['🛄', 'baggage claim', 'baggage claim luggage'],
      ['🛅', 'left luggage', 'left luggage locker'],
      ['🚹', 'men’s room', 'mens room'],
      ['🚺', 'women’s room', 'womens room'],
      ['🚼', 'baby symbol', 'baby symbol changing'],
      ['⚧️', 'transgender symbol', 'transgender symbol'],
      ['🚻', 'restroom', 'restroom toilet'],
      ['🚮', 'litter in bin sign', 'litter in bin sign'],
      ['🎦', 'cinema', 'cinema movies'],
      ['📶', 'antenna bars', 'antenna bars signal reception'],
      ['🈁', 'Japanese “here” button', 'japanese here button'],
      ['🔣', 'input symbols', 'input symbols'],
      ['ℹ️', 'information', 'information source info'],
      ['🔤', 'input latin letters', 'input latin letters abc'],
      ['🔡', 'input latin lowercase', 'input latin lowercase abc'],
      ['🔠', 'input latin uppercase', 'input latin uppercase abc'],
      ['🆖', 'NG button', 'ng button no good'],
      ['🆗', 'OK button', 'ok button fine agreed'],
      ['🆙', 'UP! button', 'up button new'],
      ['🆒', 'COOL button', 'cool button'],
      ['🆕', 'NEW button', 'new button'],
      ['🆓', 'FREE button', 'free button'],
      ['🔟', 'keycap: 10', 'keycap ten 10'],
      ['🔢', 'input numbers', 'input numbers 1234'],
      ['▶️', 'play button', 'play button start resume'],
      ['⏸️', 'pause button', 'pause button hold'],
      ['⏯️', 'play or pause button', 'play or pause button'],
      ['⏹️', 'stop button', 'stop button end'],
      ['⏺️', 'record button', 'record button'],
      ['⏭️', 'next track button', 'next track skip forward'],
      ['⏮️', 'last track button', 'last track skip back'],
      ['⏩', 'fast-forward button', 'fast forward speed'],
      ['⏪', 'fast reverse button', 'fast reverse rewind'],
      ['🔀', 'shuffle tracks button', 'shuffle random tracks'],
      ['🔁', 'repeat button', 'repeat loop'],
      ['🔂', 'repeat single button', 'repeat single loop one'],
      ['◀️', 'reverse button', 'reverse play back'],
      ['🔼', 'upwards button', 'upwards button up'],
      ['🔽', 'downwards button', 'downwards button down'],
      ['⏫', 'fast up button', 'fast up double'],
      ['⏬', 'fast down button', 'fast down double'],
      ['➡️', 'right arrow', 'right arrow next forward'],
      ['⬅️', 'left arrow', 'left arrow back previous'],
      ['⬆️', 'up arrow', 'up arrow above'],
      ['⬇️', 'down arrow', 'down arrow below'],
      ['↗️', 'up-right arrow', 'up right arrow diagonal'],
      ['↘️', 'down-right arrow', 'down right arrow diagonal'],
      ['↙️', 'down-left arrow', 'down left arrow diagonal'],
      ['↖️', 'up-left arrow', 'up left arrow diagonal'],
      ['↕️', 'up-down arrow', 'up down arrow vertical'],
      ['↔️', 'left-right arrow', 'left right arrow horizontal'],
      ['↩️', 'right arrow curving left', 'right arrow curving left reply back'],
      ['↪️', 'left arrow curving right', 'left arrow curving right forward'],
      ['⤴️', 'right arrow curving up', 'right arrow curving up'],
      ['⤵️', 'right arrow curving down', 'right arrow curving down'],
      ['🔃', 'clockwise vertical arrows', 'clockwise vertical arrows refresh'],
      ['🔄', 'counterclockwise arrows button', 'counterclockwise arrows refresh sync retry'],
      ['🔙', 'BACK arrow', 'back arrow'],
      ['🔚', 'END arrow', 'end arrow finish'],
      ['🔛', 'ON! arrow', 'on arrow'],
      ['🔝', 'TOP arrow', 'top arrow best'],
      ['🔜', 'SOON arrow', 'soon arrow later'],
      ['〰️', 'wavy dash', 'wavy dash'],
      ['➰', 'curly loop', 'curly loop'],
      ['➿', 'double curly loop', 'double curly loop'],
      ['✔️', 'check mark', 'check mark tick done'],
      ['☑️', 'check box with check', 'check box with check ticked done'],
      ['🔘', 'radio button', 'radio button select'],
      ['🔴', 'red circle', 'red circle dot'],
      ['🟠', 'orange circle', 'orange circle dot'],
      ['🟡', 'yellow circle', 'yellow circle dot'],
      ['🟢', 'green circle', 'green circle dot go'],
      ['🔵', 'blue circle', 'blue circle dot'],
      ['🟣', 'purple circle', 'purple circle dot'],
      ['⚫', 'black circle', 'black circle dot'],
      ['⚪', 'white circle', 'white circle dot'],
      ['🟤', 'brown circle', 'brown circle dot'],
      ['🔺', 'red triangle pointed up', 'red triangle pointed up'],
      ['🔻', 'red triangle pointed down', 'red triangle pointed down'],
      ['🔸', 'small orange diamond', 'small orange diamond'],
      ['🔹', 'small blue diamond', 'small blue diamond'],
      ['🔶', 'large orange diamond', 'large orange diamond'],
      ['🔷', 'large blue diamond', 'large blue diamond'],
      ['🔳', 'white square button', 'white square button'],
      ['🔲', 'black square button', 'black square button'],
      ['▪️', 'black small square', 'black small square'],
      ['▫️', 'white small square', 'white small square'],
      ['◾', 'black medium-small square', 'black medium small square'],
      ['◽', 'white medium-small square', 'white medium small square'],
      ['◼️', 'black medium square', 'black medium square'],
      ['◻️', 'white medium square', 'white medium square'],
      ['⬛', 'black large square', 'black large square'],
      ['⬜', 'white large square', 'white large square'],
      ['🟥', 'red square', 'red square'],
      ['🟧', 'orange square', 'orange square'],
      ['🟨', 'yellow square', 'yellow square'],
      ['🟩', 'green square', 'green square'],
      ['🟦', 'blue square', 'blue square'],
      ['🟪', 'purple square', 'purple square'],
      ['🟫', 'brown square', 'brown square'],
      ['♠️', 'spade suit', 'spade suit cards'],
      ['♥️', 'heart suit', 'heart suit cards'],
      ['♦️', 'diamond suit', 'diamond suit cards'],
      ['♣️', 'club suit', 'club suit cards'],
      ['🃏', 'joker', 'joker card wild'],
      ['🀄', 'mahjong red dragon', 'mahjong red dragon'],
      ['🎴', 'flower playing cards', 'flower playing cards'],
      ['🔇', 'muted speaker', 'muted speaker mute silent'],
      ['🔈', 'speaker low volume', 'speaker low volume'],
      ['🔉', 'speaker medium volume', 'speaker medium volume'],
      ['🔊', 'speaker high volume', 'speaker high volume loud'],
      ['📢', 'loudspeaker', 'loudspeaker announce'],
      ['📣', 'megaphone', 'megaphone cheer announce'],
      ['📯', 'postal horn', 'postal horn'],
      ['🔔', 'bell', 'bell notification alert'],
      ['🔕', 'bell with slash', 'bell with slash mute notifications'],
      ['🎵', 'musical note', 'musical note music'],
      ['🎶', 'musical notes', 'musical notes music'],
      ['🏁', 'chequered flag', 'chequered flag finish race done'],
      ['🚩', 'triangular flag', 'triangular flag marker'],
      ['🎌', 'crossed flags', 'crossed flags japan'],
      ['🏴', 'black flag', 'black flag'],
      ['🏳️', 'white flag', 'white flag surrender'],
      ['🏳️‍🌈', 'rainbow flag', 'rainbow flag pride lgbt'],
    ],
  },
];

/** Every emoji the picker offers, flattened. */
export const ALL_PICKER_EMOJIS: readonly string[] = EMOJI_GROUPS.flatMap((group) =>
  group.emojis.map(([emoji]) => emoji),
);

/** The whole catalogue as one flat list, for searching across categories. */
const ALL_ENTRIES: readonly EmojiEntry[] = EMOJI_GROUPS.flatMap((group) => group.emojis);

const NAMES = new Map<string, string>(ALL_ENTRIES.map(([emoji, name]) => [emoji, name]));

/**
 * What one emoji is called, for anywhere a glyph alone is not enough — the
 * list of who reacted, which is headed by the reaction it belongs to.
 *
 * Null for anything not in the catalogue. A reaction can be any emoji the
 * server accepts, so one can arrive from a client offering a wider set than
 * this one, or in a form this list does not carry (a skin tone, say). Nothing
 * is invented for those: the heading is dropped and the names stand alone.
 */
export function emojiName(emoji: string): string | null {
  return NAMES.get(emoji) ?? null;
}

/**
 * What a button that leaves this reaction is called, for anyone who cannot see
 * the glyph on it.
 *
 * The shared contract can only manage "React with 🎉": it knows the quick
 * three by name and nothing else, and a screen reader handed the bare glyph
 * falls back to whatever its own table calls it — which is why the heading
 * over a list of names and the name announced for the same chip used to
 * disagree. The catalogue is here, so the button can say what it is.
 */
export function reactionButtonLabel(emoji: string): string {
  const named = reactionName(emoji);
  if (named) return named;
  const known = emojiName(emoji);
  return known ? `React with ${known}` : reactionLabel(emoji);
}

/**
 * Emoji whose terms match every word typed, in catalogue order.
 *
 * Each typed word has to match the *start* of one of an emoji's terms, so
 * "car" finds the car and the carrot but not the postcard, and "he" finds
 * hearts without also finding everything that mentions "the". Several words
 * narrow rather than widen: "red heart" is the emoji that is both.
 */
export function searchEmojis(query: string): readonly EmojiEntry[] {
  const words = query.toLowerCase().split(/\s+/).filter(Boolean);
  if (words.length === 0) return [];

  return ALL_ENTRIES.filter(([, , terms]) => {
    const candidates = terms.split(' ');
    return words.every((word) => candidates.some((term) => term.startsWith(word)));
  });
}
