/**
 * What the reaction picker offers (F18).
 *
 * Presentation data, so it lives with the board rather than in the shared
 * contract: the server does not care which emoji a client puts in front of
 * people, only that what comes back is one emoji. Adding a row here needs no
 * migration and no agreement with any other module.
 *
 * A curated catalogue rather than every codepoint Unicode calls pictographic.
 * The full set runs past 1900 glyphs, most of them regional indicators and
 * clock faces nobody reaches for mid-brainstorm, and a grid that long buries
 * the ones people do want. These are the emoji in ordinary use, grouped the
 * way every picker groups them.
 *
 * Each entry is the glyph and the words someone might type to find it. The
 * terms are what makes the search box work at all: an emoji carries no name of
 * its own that a browser can be asked for, so anything not written here is
 * findable only by scrolling to it.
 *
 * The grids are laid out one entry per line and held that way with
 * `prettier-ignore`, so a category reads as a list you can scan for a
 * duplicate rather than as a reflowed paragraph of punctuation.
 */

/** A glyph and the space-separated words that should find it. */
export type EmojiEntry = readonly [emoji: string, terms: string];

export interface EmojiGroup {
  /** Tab label, and the accessible name of the tab. */
  name: string;
  /** The glyph on the tab itself. */
  icon: string;
  emojis: readonly EmojiEntry[];
}

export const EMOJI_GROUPS: readonly EmojiGroup[] = [
  {
    name: 'Smileys',
    icon: '😀',
    // prettier-ignore
    emojis: [
      ['😀', 'grinning grin happy smile face'],
      ['😃', 'smiley happy joy open smile'],
      ['😄', 'smile happy laugh eyes joy'],
      ['😁', 'beaming grin teeth happy'],
      ['😆', 'laughing satisfied haha laugh'],
      ['😅', 'sweat smile relief nervous laugh'],
      ['🤣', 'rofl rolling floor laughing lol'],
      ['😂', 'joy tears laughing cry lol funny'],
      ['🙂', 'slight smile fine ok'],
      ['🙃', 'upside down silly irony sarcasm'],
      ['😉', 'wink flirt joke'],
      ['😊', 'blush smile happy warm'],
      ['😇', 'innocent halo angel good'],
      ['🥰', 'smiling hearts love adore'],
      ['😍', 'heart eyes love crush amazing'],
      ['🤩', 'star struck excited amazed wow'],
      ['😘', 'kiss blow heart'],
      ['😗', 'kissing kiss'],
      ['😚', 'kissing closed eyes kiss'],
      ['😙', 'kissing smiling eyes kiss'],
      ['🥲', 'smiling tear happy sad bittersweet'],
      ['😋', 'yum tasty delicious tongue savour'],
      ['😛', 'tongue out playful cheeky'],
      ['😜', 'winking tongue joke crazy'],
      ['🤪', 'zany crazy goofy wild silly'],
      ['😝', 'squinting tongue silly yuck'],
      ['🤑', 'money mouth rich dollar profit'],
      ['🤗', 'hugging hug embrace warm'],
      ['🤭', 'hand over mouth oops giggle'],
      ['🤫', 'shushing quiet secret hush'],
      ['🤔', 'thinking think hmm consider unsure'],
      ['🤐', 'zipper mouth silent secret'],
      ['🤨', 'raised eyebrow skeptical suspicious doubt'],
      ['😐', 'neutral blank meh deadpan'],
      ['😑', 'expressionless blank flat'],
      ['😶', 'no mouth speechless silence'],
      ['😏', 'smirk smug knowing'],
      ['😒', 'unamused annoyed unimpressed'],
      ['🙄', 'rolling eyes exasperated whatever'],
      ['😬', 'grimacing awkward cringe yikes'],
      ['😌', 'relieved calm content peace'],
      ['😔', 'pensive sad down glum'],
      ['😪', 'sleepy tired drowsy'],
      ['🤤', 'drooling drool hungry want'],
      ['😴', 'sleeping asleep zzz snore'],
      ['😷', 'mask sick medical face'],
      ['🤒', 'thermometer sick fever ill'],
      ['🤕', 'head bandage hurt injured'],
      ['🤢', 'nauseated sick disgusted gross'],
      ['🤮', 'vomiting sick puke gross'],
      ['🥵', 'hot heat sweating overheated'],
      ['🥶', 'cold freezing frozen ice'],
      ['🥴', 'woozy dizzy drunk tipsy'],
      ['😵', 'dizzy knocked out crossed eyes'],
      ['🤯', 'exploding head mind blown shocked'],
      ['🤠', 'cowboy hat yeehaw'],
      ['🥳', 'partying party celebrate hat horn'],
      ['🥸', 'disguised glasses incognito nose'],
      ['😎', 'sunglasses cool shades'],
      ['🤓', 'nerd geek glasses'],
      ['🧐', 'monocle inspect scrutiny examine'],
      ['😕', 'confused unsure puzzled'],
      ['😟', 'worried concerned anxious'],
      ['🙁', 'slight frown sad unhappy'],
      ['😮', 'open mouth surprised wow oh'],
      ['😯', 'hushed surprised stunned'],
      ['😲', 'astonished shocked gasp'],
      ['😳', 'flushed embarrassed blush shocked'],
      ['🥺', 'pleading puppy eyes beg please'],
      ['😦', 'frowning open mouth worried'],
      ['😨', 'fearful scared afraid'],
      ['😰', 'anxious sweat nervous worried'],
      ['😥', 'sad relieved disappointed'],
      ['😢', 'crying tear sad upset'],
      ['😭', 'sobbing loudly crying bawling sad'],
      ['😱', 'screaming fear scream shocked horror'],
      ['😖', 'confounded frustrated distress'],
      ['😣', 'persevere struggle strain'],
      ['😞', 'disappointed sad let down'],
      ['😓', 'downcast sweat sad hard'],
      ['😩', 'weary tired frustrated'],
      ['😫', 'tired exhausted fed up'],
      ['🥱', 'yawning bored tired'],
      ['😤', 'triumph steam angry huff determined'],
      ['😡', 'pouting angry mad rage red'],
      ['😠', 'angry mad annoyed cross'],
      ['🤬', 'cursing swearing symbols angry'],
      ['😈', 'smiling devil imp mischief evil'],
      ['💀', 'skull dead death bones'],
      ['💩', 'poop pile crap dung'],
      ['🤡', 'clown circus joker'],
      ['👻', 'ghost boo spooky halloween'],
      ['👽', 'alien extraterrestrial ufo space'],
      ['🤖', 'robot bot machine ai'],
      ['😺', 'grinning cat smile'],
      ['😹', 'cat joy tears laughing'],
      ['😻', 'heart eyes cat love'],
      ['🙀', 'weary cat shocked scream'],
      ['😿', 'crying cat sad'],
      ['😾', 'pouting cat angry'],
    ],
  },
  {
    name: 'Gestures',
    icon: '👍',
    // prettier-ignore
    emojis: [
      ['👋', 'wave hand hello goodbye hi'],
      ['🤚', 'raised back hand stop'],
      ['🖐️', 'hand fingers splayed five'],
      ['✋', 'raised hand stop high five'],
      ['🖖', 'vulcan salute spock live long'],
      ['👌', 'ok hand perfect fine'],
      ['🤌', 'pinched fingers italian gesture'],
      ['🤏', 'pinching small little bit'],
      ['✌️', 'victory peace two fingers'],
      ['🤞', 'crossed fingers luck hope'],
      ['🤟', 'love you gesture hand'],
      ['🤘', 'horns rock metal'],
      ['🤙', 'call me shaka hang loose'],
      ['👈', 'point left backhand'],
      ['👉', 'point right backhand'],
      ['👆', 'point up backhand above'],
      ['👇', 'point down backhand below'],
      ['☝️', 'index point up one'],
      ['👍', 'thumbs up yes agree like approve good'],
      ['👎', 'thumbs down no disagree dislike bad'],
      ['✊', 'raised fist solidarity power'],
      ['👊', 'fist bump punch'],
      ['🤛', 'left facing fist bump'],
      ['🤜', 'right facing fist bump'],
      ['👏', 'clap applause bravo well done'],
      ['🙌', 'raising hands celebrate praise hooray'],
      ['👐', 'open hands hug welcome'],
      ['🤲', 'palms up together offer pray'],
      ['🤝', 'handshake deal agree partner'],
      ['🙏', 'folded hands please thanks pray'],
      ['✍️', 'writing hand write note'],
      ['💅', 'nail polish manicure sass'],
      ['🤳', 'selfie phone camera'],
      ['💪', 'flexed biceps strong muscle power'],
      ['🦾', 'mechanical arm prosthetic robot'],
      ['🦿', 'mechanical leg prosthetic robot'],
      ['🦵', 'leg limb kick'],
      ['🦶', 'foot kick stomp'],
      ['👂', 'ear hear listen'],
      ['👃', 'nose smell'],
      ['🧠', 'brain mind smart think'],
      ['🫀', 'anatomical heart organ pulse'],
      ['👀', 'eyes look watch see'],
      ['👁️', 'eye look see'],
      ['👅', 'tongue taste lick'],
      ['👄', 'mouth lips'],
      ['💋', 'kiss mark lips lipstick'],
      ['🩸', 'blood drop donate'],
      ['👶', 'baby infant child'],
      ['🧒', 'child kid young'],
      ['👦', 'boy child'],
      ['👧', 'girl child'],
      ['🧑', 'person adult someone'],
      ['👨', 'man adult male'],
      ['👩', 'woman adult female'],
      ['🧓', 'older person elder'],
      ['👴', 'old man grandfather elder'],
      ['👵', 'old woman grandmother elder'],
      ['🙋', 'raising hand question volunteer me'],
      ['🙆', 'gesturing ok arms yes'],
      ['🙅', 'gesturing no stop refuse'],
      ['💁', 'tipping hand information sassy'],
      ['🙇', 'bowing sorry apology respect'],
      ['🤦', 'facepalm disbelief frustration'],
      ['🤷', 'shrug dunno whatever unsure'],
      ['🧑‍💻', 'technologist developer coding laptop'],
      ['🕵️', 'detective spy investigate'],
      ['💂', 'guard soldier'],
      ['🥷', 'ninja stealth'],
      ['🧑‍🚀', 'astronaut space rocket'],
    ],
  },
  {
    name: 'Nature',
    icon: '🌿',
    // prettier-ignore
    emojis: [
      ['🐶', 'dog puppy pet face'],
      ['🐱', 'cat kitten pet face'],
      ['🐭', 'mouse rodent'],
      ['🐹', 'hamster pet rodent'],
      ['🐰', 'rabbit bunny hare'],
      ['🦊', 'fox clever'],
      ['🐻', 'bear'],
      ['🐼', 'panda bear'],
      ['🐨', 'koala'],
      ['🐯', 'tiger face'],
      ['🦁', 'lion king'],
      ['🐮', 'cow face'],
      ['🐷', 'pig face'],
      ['🐸', 'frog toad'],
      ['🐵', 'monkey face'],
      ['🙈', 'see no evil monkey hide'],
      ['🙉', 'hear no evil monkey'],
      ['🙊', 'speak no evil monkey quiet'],
      ['🐒', 'monkey ape'],
      ['🦍', 'gorilla ape'],
      ['🐔', 'chicken hen'],
      ['🐧', 'penguin'],
      ['🐦', 'bird'],
      ['🐤', 'chick baby bird'],
      ['🦆', 'duck'],
      ['🦅', 'eagle bird'],
      ['🦉', 'owl wise bird'],
      ['🦇', 'bat vampire'],
      ['🐺', 'wolf'],
      ['🐗', 'boar pig'],
      ['🐴', 'horse face'],
      ['🦄', 'unicorn magic rare'],
      ['🐝', 'bee honey buzz'],
      ['🐛', 'bug caterpillar insect'],
      ['🦋', 'butterfly transform'],
      ['🐌', 'snail slow'],
      ['🐞', 'ladybug beetle luck'],
      ['🐜', 'ant insect'],
      ['🕷️', 'spider web'],
      ['🦂', 'scorpion'],
      ['🐢', 'turtle tortoise slow'],
      ['🐍', 'snake serpent'],
      ['🦎', 'lizard gecko'],
      ['🦖', 'dinosaur trex rex'],
      ['🐙', 'octopus tentacles'],
      ['🦑', 'squid'],
      ['🦐', 'shrimp prawn'],
      ['🦀', 'crab'],
      ['🐡', 'blowfish pufferfish'],
      ['🐠', 'tropical fish'],
      ['🐟', 'fish'],
      ['🐬', 'dolphin'],
      ['🐳', 'whale spouting'],
      ['🐋', 'whale big'],
      ['🦈', 'shark'],
      ['🐊', 'crocodile alligator'],
      ['🐅', 'tiger'],
      ['🦓', 'zebra stripes'],
      ['🦛', 'hippopotamus hippo'],
      ['🐘', 'elephant'],
      ['🦏', 'rhinoceros rhino'],
      ['🐪', 'camel desert'],
      ['🦒', 'giraffe tall'],
      ['🦘', 'kangaroo jump'],
      ['🐄', 'cow cattle'],
      ['🐎', 'horse racehorse'],
      ['🐖', 'pig hog'],
      ['🐑', 'sheep ewe wool'],
      ['🦙', 'llama alpaca'],
      ['🐐', 'goat'],
      ['🦌', 'deer stag'],
      ['🐕', 'dog'],
      ['🐈', 'cat'],
      ['🦔', 'hedgehog'],
      ['🌵', 'cactus desert'],
      ['🎄', 'christmas tree holiday'],
      ['🌲', 'evergreen tree pine'],
      ['🌳', 'deciduous tree'],
      ['🌴', 'palm tree tropical'],
      ['🪴', 'potted plant houseplant'],
      ['🌱', 'seedling sprout growth new'],
      ['🌿', 'herb leaf plant'],
      ['☘️', 'shamrock clover irish'],
      ['🍀', 'four leaf clover luck lucky'],
      ['🍃', 'leaves wind flutter'],
      ['🍂', 'fallen leaves autumn fall'],
      ['🍁', 'maple leaf autumn canada'],
      ['🍄', 'mushroom fungus'],
      ['🐚', 'shell spiral beach'],
      ['💐', 'bouquet flowers gift'],
      ['🌷', 'tulip flower'],
      ['🌹', 'rose flower love'],
      ['🥀', 'wilted flower dead'],
      ['🌺', 'hibiscus flower tropical'],
      ['🌸', 'cherry blossom sakura flower spring'],
      ['🌼', 'blossom flower daisy'],
      ['🌻', 'sunflower flower'],
      ['🌞', 'sun face bright day'],
      ['🌝', 'full moon face'],
      ['🌛', 'first quarter moon face'],
      ['🌚', 'new moon face dark'],
      ['🌕', 'full moon night'],
      ['🌙', 'crescent moon night'],
      ['🌎', 'earth globe americas world planet'],
      ['🪐', 'ringed planet saturn space'],
      ['💫', 'dizzy stars sparkle'],
      ['⭐', 'star favourite'],
      ['🌟', 'glowing star sparkle shine'],
      ['✨', 'sparkles magic shine new'],
      ['⚡', 'high voltage lightning fast energy'],
      ['☄️', 'comet space'],
      ['💥', 'collision boom explosion impact'],
      ['🔥', 'fire flame hot lit burn'],
      ['🌪️', 'tornado cyclone storm'],
      ['🌈', 'rainbow pride colour'],
      ['☀️', 'sun sunny bright clear'],
      ['⛅', 'sun behind cloud partly cloudy'],
      ['☁️', 'cloud cloudy overcast'],
      ['🌧️', 'cloud rain rainy wet'],
      ['⛈️', 'thunderstorm storm lightning rain'],
      ['❄️', 'snowflake snow cold winter'],
      ['☃️', 'snowman snow winter'],
      ['⛄', 'snowman without snow winter'],
      ['💨', 'dashing wind fast gust'],
      ['💧', 'droplet water drop'],
      ['💦', 'sweat droplets water splash'],
      ['☔', 'umbrella rain wet'],
      ['🌊', 'wave water ocean sea'],
    ],
  },
  {
    name: 'Food',
    icon: '🍕',
    // prettier-ignore
    emojis: [
      ['🍏', 'green apple fruit'],
      ['🍎', 'red apple fruit'],
      ['🍐', 'pear fruit'],
      ['🍊', 'tangerine orange fruit citrus'],
      ['🍋', 'lemon fruit citrus sour'],
      ['🍌', 'banana fruit'],
      ['🍉', 'watermelon fruit summer'],
      ['🍇', 'grapes fruit wine'],
      ['🍓', 'strawberry fruit berry'],
      ['🫐', 'blueberries fruit berry'],
      ['🍈', 'melon fruit'],
      ['🍒', 'cherries fruit'],
      ['🍑', 'peach fruit'],
      ['🥭', 'mango fruit tropical'],
      ['🍍', 'pineapple fruit tropical'],
      ['🥥', 'coconut fruit tropical'],
      ['🥝', 'kiwi fruit'],
      ['🍅', 'tomato vegetable salad'],
      ['🍆', 'aubergine eggplant vegetable'],
      ['🥑', 'avocado fruit toast'],
      ['🥦', 'broccoli vegetable green'],
      ['🥬', 'leafy green lettuce vegetable'],
      ['🥒', 'cucumber pickle vegetable'],
      ['🌶️', 'hot pepper chilli spicy'],
      ['🌽', 'corn maize cob'],
      ['🥕', 'carrot vegetable'],
      ['🧄', 'garlic'],
      ['🧅', 'onion'],
      ['🥔', 'potato'],
      ['🍠', 'roasted sweet potato yam'],
      ['🥐', 'croissant pastry bread'],
      ['🥯', 'bagel bread'],
      ['🍞', 'bread loaf'],
      ['🥖', 'baguette bread french'],
      ['🧀', 'cheese wedge'],
      ['🥚', 'egg'],
      ['🍳', 'cooking fried egg pan breakfast'],
      ['🧈', 'butter'],
      ['🥞', 'pancakes breakfast stack'],
      ['🧇', 'waffle breakfast'],
      ['🥓', 'bacon breakfast'],
      ['🍔', 'hamburger burger fast food'],
      ['🍟', 'fries chips fast food'],
      ['🍕', 'pizza slice'],
      ['🌭', 'hot dog sausage'],
      ['🥪', 'sandwich lunch'],
      ['🌮', 'taco mexican'],
      ['🌯', 'burrito wrap mexican'],
      ['🥙', 'stuffed flatbread kebab pita'],
      ['🧆', 'falafel'],
      ['🥘', 'shallow pan of food paella'],
      ['🍝', 'spaghetti pasta italian'],
      ['🍜', 'steaming bowl ramen noodles'],
      ['🍲', 'pot of food stew soup'],
      ['🍛', 'curry rice'],
      ['🍣', 'sushi japanese'],
      ['🍱', 'bento box japanese lunch'],
      ['🥟', 'dumpling gyoza'],
      ['🍤', 'fried shrimp prawn tempura'],
      ['🍙', 'rice ball onigiri'],
      ['🍚', 'cooked rice'],
      ['🍥', 'fish cake narutomaki'],
      ['🥠', 'fortune cookie'],
      ['🍦', 'soft ice cream dessert'],
      ['🍰', 'shortcake cake slice dessert'],
      ['🎂', 'birthday cake celebrate'],
      ['🧁', 'cupcake dessert'],
      ['🥧', 'pie dessert'],
      ['🍫', 'chocolate bar sweet'],
      ['🍬', 'candy sweet'],
      ['🍭', 'lollipop candy sweet'],
      ['🍩', 'doughnut donut sweet'],
      ['🍪', 'cookie biscuit sweet'],
      ['☕', 'hot beverage coffee tea'],
      ['🍵', 'teacup tea green'],
      ['🧃', 'beverage box juice'],
      ['🥤', 'cup straw soda drink'],
      ['🧋', 'bubble tea boba'],
      ['🍺', 'beer mug pint'],
      ['🍻', 'clinking beer mugs cheers'],
      ['🥂', 'clinking glasses cheers celebrate toast'],
      ['🍷', 'wine glass red'],
      ['🥃', 'tumbler whisky glass'],
      ['🍸', 'cocktail martini glass'],
      ['🍾', 'bottle popping champagne celebrate'],
      ['🧉', 'mate drink'],
      ['🧊', 'ice cube cold frozen'],
    ],
  },
  {
    name: 'Activity',
    icon: '⚽',
    // prettier-ignore
    emojis: [
      ['⚽', 'soccer football ball sport'],
      ['🏀', 'basketball ball sport'],
      ['🏈', 'american football ball sport'],
      ['⚾', 'baseball ball sport'],
      ['🥎', 'softball ball sport'],
      ['🎾', 'tennis ball sport'],
      ['🏐', 'volleyball ball sport'],
      ['🏉', 'rugby football ball sport'],
      ['🥏', 'flying disc frisbee'],
      ['🎱', 'pool 8 ball billiards snooker'],
      ['🏓', 'ping pong table tennis'],
      ['🏸', 'badminton shuttlecock'],
      ['🥅', 'goal net sport'],
      ['⛳', 'golf flag hole'],
      ['🏹', 'bow and arrow archery target'],
      ['🎣', 'fishing pole fish'],
      ['🥊', 'boxing glove fight'],
      ['🥋', 'martial arts uniform karate judo'],
      ['🎽', 'running shirt sash race'],
      ['🛹', 'skateboard skate'],
      ['🛼', 'roller skate'],
      ['🛷', 'sled sledge snow'],
      ['⛸️', 'ice skate skating'],
      ['🥌', 'curling stone'],
      ['🎿', 'skis skiing snow'],
      ['⛷️', 'skier skiing snow'],
      ['🏂', 'snowboarder snowboard snow'],
      ['🏋️', 'weight lifting gym workout'],
      ['🤸', 'cartwheel gymnastics'],
      ['🤺', 'fencing sword'],
      ['🤾', 'handball sport'],
      ['🏌️', 'golfing golf swing'],
      ['🏇', 'horse racing jockey'],
      ['🧘', 'lotus position yoga meditation calm'],
      ['🏄', 'surfing surf wave'],
      ['🏊', 'swimming swim pool'],
      ['🤽', 'water polo'],
      ['🚣', 'rowing boat row'],
      ['🚴', 'biking cycling bicycle'],
      ['🚵', 'mountain biking cycling'],
      ['🎪', 'circus tent carnival'],
      ['🎭', 'performing arts theatre drama masks'],
      ['🎨', 'artist palette paint art design'],
      ['🎬', 'clapper board film movie action'],
      ['🎤', 'microphone sing mic'],
      ['🎧', 'headphone music listen audio'],
      ['🎼', 'musical score sheet music'],
      ['🎹', 'musical keyboard piano'],
      ['🥁', 'drum beat'],
      ['🎷', 'saxophone jazz'],
      ['🎺', 'trumpet brass'],
      ['🎸', 'guitar rock'],
      ['🎻', 'violin strings'],
      ['🎲', 'game die dice random chance'],
      ['♟️', 'chess pawn strategy'],
      ['🎯', 'direct hit bullseye target goal'],
      ['🎳', 'bowling strike pins'],
      ['🎮', 'video game controller gaming'],
      ['🕹️', 'joystick arcade gaming'],
      ['🧩', 'puzzle piece jigsaw fit'],
      ['🚗', 'car automobile drive'],
      ['🚕', 'taxi cab'],
      ['🚌', 'bus'],
      ['🏎️', 'racing car fast speed'],
      ['🚓', 'police car'],
      ['🚑', 'ambulance emergency'],
      ['🚒', 'fire engine truck'],
      ['🚚', 'delivery truck lorry'],
      ['🚜', 'tractor farm'],
      ['🛵', 'motor scooter moped'],
      ['🏍️', 'motorcycle motorbike'],
      ['🚲', 'bicycle bike cycle'],
      ['✈️', 'airplane flight travel plane'],
      ['🚀', 'rocket launch ship fast space'],
      ['🛸', 'flying saucer ufo alien'],
      ['🚁', 'helicopter'],
      ['⛵', 'sailboat sailing yacht'],
      ['🚤', 'speedboat boat'],
      ['🛳️', 'passenger ship cruise'],
      ['🚂', 'locomotive train steam'],
      ['🗺️', 'world map travel plan'],
      ['🗿', 'moai statue stone'],
      ['🗽', 'statue of liberty new york'],
      ['🗼', 'tokyo tower'],
      ['🏰', 'castle fortress'],
      ['🎡', 'ferris wheel fair'],
      ['🎢', 'roller coaster theme park'],
      ['🎠', 'carousel horse fair'],
      ['⛲', 'fountain water'],
      ['🏖️', 'beach umbrella holiday sand'],
      ['🏝️', 'desert island beach tropical'],
      ['🏔️', 'snow capped mountain peak'],
      ['🌋', 'volcano eruption lava'],
      ['🏕️', 'camping tent outdoors'],
      ['🏡', 'house with garden home'],
      ['🏢', 'office building work'],
      ['🏫', 'school university education'],
      ['🏥', 'hospital medical'],
      ['⛺', 'tent camping'],
      ['🌅', 'sunrise morning dawn'],
      ['🌄', 'sunrise over mountains morning'],
      ['🌆', 'cityscape dusk evening city'],
      ['🌃', 'night with stars city'],
      ['🌉', 'bridge at night'],
      ['🎇', 'sparkler firework celebrate'],
      ['🎆', 'fireworks celebrate new year'],
      ['🎉', 'party popper celebrate congrats hooray'],
      ['🎊', 'confetti ball celebrate party'],
      ['🎈', 'balloon party celebrate'],
      ['🎁', 'wrapped gift present birthday'],
    ],
  },
  {
    name: 'Objects',
    icon: '💡',
    // prettier-ignore
    emojis: [
      ['⌚', 'watch time wrist'],
      ['📱', 'mobile phone smartphone cell'],
      ['💻', 'laptop computer work'],
      ['⌨️', 'keyboard typing'],
      ['🖥️', 'desktop computer monitor screen'],
      ['🖨️', 'printer print'],
      ['🖱️', 'computer mouse click'],
      ['💽', 'minidisc computer disk'],
      ['💾', 'floppy disk save'],
      ['💿', 'optical disk cd'],
      ['📷', 'camera photo'],
      ['📸', 'camera with flash photo'],
      ['📹', 'video camera record'],
      ['🎥', 'movie camera film'],
      ['📽️', 'film projector cinema'],
      ['📞', 'telephone receiver call'],
      ['☎️', 'telephone landline call'],
      ['📟', 'pager beeper'],
      ['📠', 'fax machine'],
      ['📺', 'television tv screen'],
      ['📻', 'radio broadcast'],
      ['🎙️', 'studio microphone podcast record'],
      ['⏱️', 'stopwatch timer'],
      ['⏰', 'alarm clock wake time'],
      ['⏳', 'hourglass flowing time waiting'],
      ['📡', 'satellite antenna signal'],
      ['🔋', 'battery power charge'],
      ['🔌', 'electric plug power'],
      ['💡', 'light bulb idea insight bright'],
      ['🔦', 'flashlight torch light'],
      ['🕯️', 'candle light'],
      ['🧯', 'fire extinguisher safety'],
      ['🛢️', 'oil drum barrel'],
      ['💸', 'money with wings spending cost'],
      ['💵', 'dollar banknote money cash'],
      ['💰', 'money bag budget rich'],
      ['💳', 'credit card payment'],
      ['💎', 'gem stone diamond precious'],
      ['⚖️', 'balance scale justice weigh trade off'],
      ['🪜', 'ladder climb'],
      ['🧰', 'toolbox tools'],
      ['🔧', 'wrench spanner fix tool'],
      ['🔨', 'hammer build tool'],
      ['⚒️', 'hammer and pick tools'],
      ['🛠️', 'hammer and wrench tools build maintenance'],
      ['⛏️', 'pick mine tool'],
      ['🔩', 'nut and bolt hardware'],
      ['⚙️', 'gear cog settings mechanism'],
      ['🧱', 'brick wall build'],
      ['⛓️', 'chains links blocked'],
      ['🧲', 'magnet attract'],
      ['🔫', 'water pistol gun'],
      ['💣', 'bomb explode risk'],
      ['🧨', 'firecracker dynamite'],
      ['🪓', 'axe chop'],
      ['🔪', 'kitchen knife cut chef'],
      ['🛡️', 'shield protect defence'],
      ['🚬', 'cigarette smoking'],
      ['⚰️', 'coffin dead funeral'],
      ['🏺', 'amphora vase pot'],
      ['🔮', 'crystal ball future predict fortune'],
      ['📿', 'prayer beads'],
      ['🧿', 'nazar amulet evil eye'],
      ['💈', 'barber pole'],
      ['⚗️', 'alembic chemistry experiment'],
      ['🔭', 'telescope stars vision look ahead'],
      ['🔬', 'microscope research detail science'],
      ['🕳️', 'hole gap'],
      ['💊', 'pill medicine drug'],
      ['💉', 'syringe injection vaccine'],
      ['🩹', 'adhesive bandage plaster fix patch'],
      ['🩺', 'stethoscope doctor health check'],
      ['🚪', 'door entry exit'],
      ['🛗', 'elevator lift'],
      ['🪑', 'chair seat'],
      ['🚿', 'shower wash'],
      ['🛁', 'bathtub bath'],
      ['🧴', 'lotion bottle soap'],
      ['🧷', 'safety pin'],
      ['🧹', 'broom sweep clean tidy'],
      ['🧺', 'basket laundry'],
      ['🧻', 'roll of paper toilet'],
      ['🪣', 'bucket pail'],
      ['🧼', 'soap wash clean'],
      ['🪥', 'toothbrush'],
      ['🧽', 'sponge clean'],
      ['🔑', 'key unlock access'],
      ['🗝️', 'old key unlock secret'],
      ['🔒', 'locked lock secure private'],
      ['🔓', 'unlocked open access'],
      ['📔', 'notebook decorative cover'],
      ['📕', 'closed book read'],
      ['📖', 'open book read study'],
      ['📗', 'green book'],
      ['📚', 'books library reading'],
      ['📓', 'notebook notes'],
      ['📒', 'ledger accounts'],
      ['📃', 'page with curl document'],
      ['📜', 'scroll document history'],
      ['📄', 'page facing up document file'],
      ['📰', 'newspaper news'],
      ['🗞️', 'rolled up newspaper news'],
      ['📑', 'bookmark tabs sections'],
      ['🔖', 'bookmark save'],
      ['🏷️', 'label tag'],
      ['✉️', 'envelope email letter mail'],
      ['📩', 'envelope with arrow send mail'],
      ['📤', 'outbox tray send out'],
      ['📥', 'inbox tray receive in'],
      ['📦', 'package box parcel ship'],
      ['📫', 'closed mailbox raised flag mail'],
      ['📬', 'open mailbox raised flag mail'],
      ['📮', 'postbox mail'],
      ['🗳️', 'ballot box vote'],
      ['✏️', 'pencil write edit note'],
      ['✒️', 'black nib pen write'],
      ['🖋️', 'fountain pen write sign'],
      ['🖊️', 'pen write'],
      ['🖌️', 'paintbrush paint art'],
      ['🖍️', 'crayon colour draw'],
      ['📝', 'memo note write pencil paper'],
      ['💼', 'briefcase work business'],
      ['📁', 'file folder directory'],
      ['📂', 'open file folder directory'],
      ['🗂️', 'card index dividers organise'],
      ['📅', 'calendar date schedule'],
      ['📆', 'tear off calendar date'],
      ['🗒️', 'spiral notepad notes'],
      ['🗓️', 'spiral calendar schedule'],
      ['📇', 'card index contacts'],
      ['📈', 'chart increasing growth up trend'],
      ['📉', 'chart decreasing down decline'],
      ['📊', 'bar chart data metrics'],
      ['📋', 'clipboard list tasks'],
      ['📌', 'pushpin pin location'],
      ['📍', 'round pushpin location here'],
      ['📎', 'paperclip attach'],
      ['🖇️', 'linked paperclips attach'],
      ['📏', 'straight ruler measure'],
      ['📐', 'triangular ruler measure angle'],
      ['✂️', 'scissors cut trim'],
      ['🗃️', 'card file box archive'],
      ['🗄️', 'file cabinet archive storage'],
      ['🗑️', 'wastebasket bin delete trash'],
    ],
  },
  {
    name: 'Symbols',
    icon: '❤️',
    // prettier-ignore
    emojis: [
      ['❤️', 'red heart love like'],
      ['🧡', 'orange heart love'],
      ['💛', 'yellow heart love'],
      ['💚', 'green heart love'],
      ['💙', 'blue heart love'],
      ['💜', 'purple heart love'],
      ['🖤', 'black heart love dark'],
      ['🤍', 'white heart love'],
      ['🤎', 'brown heart love'],
      ['💔', 'broken heart sad breakup'],
      ['❣️', 'heart exclamation love'],
      ['💕', 'two hearts love'],
      ['💞', 'revolving hearts love'],
      ['💓', 'beating heart love pulse'],
      ['💗', 'growing heart love'],
      ['💖', 'sparkling heart love'],
      ['💘', 'heart with arrow cupid love'],
      ['💝', 'heart with ribbon gift love'],
      ['💟', 'heart decoration love'],
      ['☮️', 'peace symbol'],
      ['✝️', 'latin cross christian'],
      ['☪️', 'star and crescent islam'],
      ['🕉️', 'om hindu'],
      ['☸️', 'wheel of dharma buddhism'],
      ['✡️', 'star of david judaism'],
      ['🔯', 'six pointed star'],
      ['🕎', 'menorah judaism'],
      ['☯️', 'yin yang balance'],
      ['☦️', 'orthodox cross'],
      ['🛐', 'place of worship'],
      ['♈', 'aries zodiac'],
      ['♉', 'taurus zodiac'],
      ['♊', 'gemini zodiac'],
      ['♋', 'cancer zodiac'],
      ['♌', 'leo zodiac'],
      ['♍', 'virgo zodiac'],
      ['♎', 'libra zodiac'],
      ['♏', 'scorpio zodiac'],
      ['♐', 'sagittarius zodiac'],
      ['♑', 'capricorn zodiac'],
      ['♒', 'aquarius zodiac'],
      ['♓', 'pisces zodiac'],
      ['🆔', 'id button identity'],
      ['⚛️', 'atom science physics'],
      ['🉑', 'japanese acceptable button'],
      ['☢️', 'radioactive warning nuclear'],
      ['☣️', 'biohazard warning'],
      ['📴', 'mobile phone off'],
      ['📳', 'vibration mode phone'],
      ['🈶', 'japanese not free of charge button'],
      ['🈚', 'japanese free of charge button'],
      ['🈸', 'japanese application button'],
      ['🈺', 'japanese open for business button'],
      ['🈷️', 'japanese monthly amount button'],
      ['✴️', 'eight pointed star'],
      ['🆚', 'vs button versus'],
      ['💮', 'white flower well done'],
      ['🉐', 'japanese bargain button'],
      ['㊙️', 'japanese secret button'],
      ['㊗️', 'japanese congratulations button'],
      ['🈴', 'japanese passing grade button'],
      ['🈵', 'japanese no vacancy button'],
      ['🈹', 'japanese discount button'],
      ['🈲', 'japanese prohibited button'],
      ['🅰️', 'a button blood type'],
      ['🅱️', 'b button blood type'],
      ['🆎', 'ab button blood type'],
      ['🆑', 'cl button'],
      ['🅾️', 'o button blood type'],
      ['🆘', 'sos button help emergency'],
      ['❌', 'cross mark no wrong cancel'],
      ['⭕', 'hollow red circle correct'],
      ['🛑', 'stop sign halt'],
      ['⛔', 'no entry forbidden'],
      ['📛', 'name badge'],
      ['🚫', 'prohibited no forbidden'],
      ['💯', 'hundred points perfect score full marks'],
      ['💢', 'anger symbol mad'],
      ['♨️', 'hot springs steam'],
      ['🚷', 'no pedestrians'],
      ['🚯', 'no littering'],
      ['🚳', 'no bicycles'],
      ['🚱', 'non potable water'],
      ['🔞', 'no one under eighteen adult'],
      ['📵', 'no mobile phones'],
      ['❗', 'exclamation mark important'],
      ['❕', 'white exclamation mark'],
      ['❓', 'question mark ask unclear'],
      ['❔', 'white question mark'],
      ['‼️', 'double exclamation urgent'],
      ['⁉️', 'exclamation question surprise'],
      ['🔅', 'dim button low brightness'],
      ['🔆', 'bright button high brightness'],
      ['〽️', 'part alternation mark'],
      ['⚠️', 'warning caution risk'],
      ['🚸', 'children crossing'],
      ['🔱', 'trident emblem'],
      ['⚜️', 'fleur de lis'],
      ['🔰', 'japanese symbol for beginner'],
      ['♻️', 'recycling symbol reuse green'],
      ['✅', 'check mark button done yes complete'],
      ['🈯', 'japanese reserved button'],
      ['💹', 'chart increasing with yen money up'],
      ['❇️', 'sparkle'],
      ['✳️', 'eight spoked asterisk'],
      ['❎', 'cross mark button no'],
      ['🌐', 'globe with meridians web internet global'],
      ['💠', 'diamond with a dot'],
      ['Ⓜ️', 'circled m metro'],
      ['🌀', 'cyclone spiral swirl'],
      ['💤', 'zzz sleep bored'],
      ['🏧', 'atm sign cash'],
      ['🚾', 'water closet toilet'],
      ['♿', 'wheelchair symbol accessible accessibility'],
      ['🅿️', 'p button parking'],
      ['🈳', 'japanese vacancy button'],
      ['🈂️', 'japanese service charge button'],
      ['🛂', 'passport control border'],
      ['🛃', 'customs border'],
      ['🛄', 'baggage claim luggage'],
      ['🛅', 'left luggage locker'],
      ['🚹', 'mens room'],
      ['🚺', 'womens room'],
      ['🚼', 'baby symbol changing'],
      ['⚧️', 'transgender symbol'],
      ['🚻', 'restroom toilet'],
      ['🚮', 'litter in bin sign'],
      ['🎦', 'cinema movies'],
      ['📶', 'antenna bars signal reception'],
      ['🈁', 'japanese here button'],
      ['🔣', 'input symbols'],
      ['ℹ️', 'information source info'],
      ['🔤', 'input latin letters abc'],
      ['🔡', 'input latin lowercase abc'],
      ['🔠', 'input latin uppercase abc'],
      ['🆖', 'ng button no good'],
      ['🆗', 'ok button fine agreed'],
      ['🆙', 'up button new'],
      ['🆒', 'cool button'],
      ['🆕', 'new button'],
      ['🆓', 'free button'],
      ['🔟', 'keycap ten 10'],
      ['🔢', 'input numbers 1234'],
      ['▶️', 'play button start resume'],
      ['⏸️', 'pause button hold'],
      ['⏯️', 'play or pause button'],
      ['⏹️', 'stop button end'],
      ['⏺️', 'record button'],
      ['⏭️', 'next track skip forward'],
      ['⏮️', 'last track skip back'],
      ['⏩', 'fast forward speed'],
      ['⏪', 'fast reverse rewind'],
      ['🔀', 'shuffle random tracks'],
      ['🔁', 'repeat loop'],
      ['🔂', 'repeat single loop one'],
      ['◀️', 'reverse play back'],
      ['🔼', 'upwards button up'],
      ['🔽', 'downwards button down'],
      ['⏫', 'fast up double'],
      ['⏬', 'fast down double'],
      ['➡️', 'right arrow next forward'],
      ['⬅️', 'left arrow back previous'],
      ['⬆️', 'up arrow above'],
      ['⬇️', 'down arrow below'],
      ['↗️', 'up right arrow diagonal'],
      ['↘️', 'down right arrow diagonal'],
      ['↙️', 'down left arrow diagonal'],
      ['↖️', 'up left arrow diagonal'],
      ['↕️', 'up down arrow vertical'],
      ['↔️', 'left right arrow horizontal'],
      ['↩️', 'right arrow curving left reply back'],
      ['↪️', 'left arrow curving right forward'],
      ['⤴️', 'right arrow curving up'],
      ['⤵️', 'right arrow curving down'],
      ['🔃', 'clockwise vertical arrows refresh'],
      ['🔄', 'counterclockwise arrows refresh sync retry'],
      ['🔙', 'back arrow'],
      ['🔚', 'end arrow finish'],
      ['🔛', 'on arrow'],
      ['🔝', 'top arrow best'],
      ['🔜', 'soon arrow later'],
      ['〰️', 'wavy dash'],
      ['➰', 'curly loop'],
      ['➿', 'double curly loop'],
      ['✔️', 'check mark tick done'],
      ['☑️', 'check box with check ticked done'],
      ['🔘', 'radio button select'],
      ['🔴', 'red circle dot'],
      ['🟠', 'orange circle dot'],
      ['🟡', 'yellow circle dot'],
      ['🟢', 'green circle dot go'],
      ['🔵', 'blue circle dot'],
      ['🟣', 'purple circle dot'],
      ['⚫', 'black circle dot'],
      ['⚪', 'white circle dot'],
      ['🟤', 'brown circle dot'],
      ['🔺', 'red triangle pointed up'],
      ['🔻', 'red triangle pointed down'],
      ['🔸', 'small orange diamond'],
      ['🔹', 'small blue diamond'],
      ['🔶', 'large orange diamond'],
      ['🔷', 'large blue diamond'],
      ['🔳', 'white square button'],
      ['🔲', 'black square button'],
      ['▪️', 'black small square'],
      ['▫️', 'white small square'],
      ['◾', 'black medium small square'],
      ['◽', 'white medium small square'],
      ['◼️', 'black medium square'],
      ['◻️', 'white medium square'],
      ['⬛', 'black large square'],
      ['⬜', 'white large square'],
      ['🟥', 'red square'],
      ['🟧', 'orange square'],
      ['🟨', 'yellow square'],
      ['🟩', 'green square'],
      ['🟦', 'blue square'],
      ['🟪', 'purple square'],
      ['🟫', 'brown square'],
      ['♠️', 'spade suit cards'],
      ['♥️', 'heart suit cards'],
      ['♦️', 'diamond suit cards'],
      ['♣️', 'club suit cards'],
      ['🃏', 'joker card wild'],
      ['🀄', 'mahjong red dragon'],
      ['🎴', 'flower playing cards'],
      ['🔇', 'muted speaker mute silent'],
      ['🔈', 'speaker low volume'],
      ['🔉', 'speaker medium volume'],
      ['🔊', 'speaker high volume loud'],
      ['📢', 'loudspeaker announce'],
      ['📣', 'megaphone cheer announce'],
      ['📯', 'postal horn'],
      ['🔔', 'bell notification alert'],
      ['🔕', 'bell with slash mute notifications'],
      ['🎵', 'musical note music'],
      ['🎶', 'musical notes music'],
      ['🏁', 'chequered flag finish race done'],
      ['🚩', 'triangular flag marker'],
      ['🎌', 'crossed flags japan'],
      ['🏴', 'black flag'],
      ['🏳️', 'white flag surrender'],
      ['🏳️‍🌈', 'rainbow flag pride lgbt'],
    ],
  },
];

/** Every emoji the picker offers, flattened. */
export const ALL_PICKER_EMOJIS: readonly string[] = EMOJI_GROUPS.flatMap((group) =>
  group.emojis.map(([emoji]) => emoji),
);

/** The whole catalogue as one flat list, for searching across categories. */
const ALL_ENTRIES: readonly EmojiEntry[] = EMOJI_GROUPS.flatMap((group) => group.emojis);

/**
 * Emoji whose terms match every word typed, in catalogue order.
 *
 * Each typed word has to match the *start* of one of an emoji's terms, so
 * "car" finds the car and the carrot but not the postcard, and "he" finds
 * hearts without also finding everything that mentions "the". Several words
 * narrow rather than widen: "red heart" is the emoji that is both.
 */
export function searchEmojis(query: string): readonly EmojiEntry[] {
  const words = query.toLowerCase().split(/\s+/).filter(Boolean);
  if (words.length === 0) return [];

  return ALL_ENTRIES.filter(([, terms]) => {
    const candidates = terms.split(' ');
    return words.every((word) => candidates.some((term) => term.startsWith(word)));
  });
}
